---

# DISCLAIMER: at the moment most of started containers are planned to stop/remove manually

- name: start Zeal viewer
  docker_container:
    name: zeal
    image: wusuopu/zealdocs:{{ zeal_version }}
    state: started
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"
      - "{{ zeal_cache }}:/root/.cache/Zeal/Zeal"
      - "{{ zeal_docsets }}:/root/.local/share/Zeal/Zeal"
    env:
      DISPLAY: ":0"
  tags: [zeal]

- name: THD | prepare temporary dir
  copy:
    src: "{{ item.src }}/"
    dest: "{{ item.dest }}"
    mode: 0755
  with_items:
    - { src: "{{ role_path }}/files/thd", dest: "{{ thd_tmp_dir }}" }
    - { src: "{{ playbook_dir }}/../private/telegram", dest: "{{ thd_tmp_dir }}/private"}
  tags: [thd]

- name: THD | update config
  copy:
    content: "{{ lookup('template', 'thd_config.template') }}"
    dest: "{{ thd_tmp_dir }}/thd_config.yaml"
    mode: 0755
  tags: [thd]

- name: THD | start service
  docker_service:
    project_src: "{{ thd_tmp_dir }}"
    build: yes
  tags: [thd]

# TODO: think of syncing telegram logs somewhere
