xft_fonts:
  - { name: "Consolas", is_bold: yes, bold_keyword: "style"}
  - { name: "PTMono", is_bold: yes, bold_keyword: "style"}
  - { name: "Hack", is_bold: yes, bold_keyword: "weight"}
  - { name: "IosevkaCC", is_bold: yes, bold_keyword: "weight"}
  - { name: "mononoki", is_bold: yes, bold_keyword: "weight"}
  - { name: "Fantasque Sans Mono", is_bold: yes, bold_keyword: "style"}
  - { name: "Go Mono", is_bold: yes, bold_keyword: "style"}
  - { name: "Input Mono", is_bold: yes, bold_keyword: "weight"}
  - { name: "Noto Mono", is_bold: yes, bold_keyword: "style"}
  - { name: "Fira Code", is_bold: yes, bold_keyword: "weight"}
xft_font_current: "{{ xft_fonts.2 }}"
xft_font_size_app: 11
xft_font_size_term: 9
