---

gpg_sign_commit: yes
git_assets_dir: "{{ ansible_env.HOME }}/.git"
git_assets_dir_nixos: "{{ nixos_dotfiles_location }}/dev/git-assets"
git_assets_init_templates_dir: "{{ git_assets_dir }}/templates"
git_assets_init_templates_dir_nixos: "{{ git_assets_dir_nixos }}/templates"
git_paths:
  - { path: "{{ git_assets_init_templates_dir }}" }
  - { path: "{{ git_assets_init_templates_dir }}/hooks" }
  - { path: "{{ git_assets_init_templates_dir_nixos }}", dists: ["NixOS"], become: yes }
  - { path: "{{ git_assets_init_templates_dir_nixos }}/hooks", dists: ["NixOS"], become: yes }
git_templates:
  - { src: 'git/gitconfig.j2', dest: '/etc/gitconfig', mode: '0544', user: root, become: yes, dists: ["Gentoo"] }
  - { src: 'git/git-commit-template.j2', dest: '{{ git_assets_dir }}/git-commit-template' }
  - { src: 'git/git-commit-template.j2', dest: '{{ git_assets_dir_nixos }}/git-commit-template', user: root, become: yes, dists: ["NixOS"] }
  - { src: 'git/.gitignore', dest: '{{ git_assets_dir }}/.gitignore' }
  - { src: 'git/.gitignore', dest: '{{ git_assets_dir_nixos }}/gitignore', user: root, become: yes, dists: ["NixOS"] }
  - { src: 'git/init-templates/hooks/pre-push', dest: '{{ git_assets_init_templates_dir }}/hooks/pre-push' }
  - { src: 'git/init-templates/hooks/pre-push', dest: '{{ git_assets_init_templates_dir_nixos }}/hooks/pre-push', user: root, become: yes, dists: ["NixOS"] }
git_src_stop_words:
  - ipdb
  - wdb
git_commit_stop_words:
  - "[wip]"
  - "[WIP]"
git_credentials_expiration_seconds: 3600
