---

default_browser_executable: firefox
default_browser_cliargs: -new-tab
default_video_player_executable: mpv
shell_bookmarks_file: "{{ ansible_env.HOME }}/.bookmarks"
binaries_prefix: /usr/local/bin
emacs_config_dir: "{{ ansible_env.HOME }}/.emacs.d"
pids_dir: "{{ ansible_env.HOME }}/pids"
zsh_subconfig_path: "{{ ansible_env.HOME}}/.zsh"
user_name: octocat
user_group: octocat
xsession_wm_choices:
  - awesome
  - i3
  - sawfish
  - stumpwm
  - xmonad
xsession_current_wm: "{{ xsession_wm_choices[3] }}"
