---

nixos_config_location: /etc/nixos
nixos_dotfiles_location: "{{ nixos_config_location }}/dotfiles"
binaries_prefix:
  Gentoo:
    path: /usr/local/bin
    become: yes
  NixOS:
    path: "{{ ansible_env.HOME }}/scripts"
emacs_config_dir: "{{ ansible_env.HOME }}/.emacs.d"
pids_dir: "{{ ansible_env.HOME }}/pids"
job_vpn_datadir:
  Gentoo: /etc/custom_vpn
  NixOS: "{{ nixos_config_location }}/private/vpn/job.current"
workspace_path: "{{ ansible_env.HOME }}/workspace"
home_config_path: "{{ ansible_env.HOME }}/.config"
default_browser_executable: firefox
default_browser_cliargs: -new-tab
default_video_player_executable: mpv
default_image_viewer_executable: feh
default_ebook_viewer_executable: zathura
shell_bookmarks_file: "{{ ansible_env.HOME }}/.bookmarks"
zsh_subconfig_path: "{{ ansible_env.HOME}}/.zsh"
user_name: octocat
user_group: octocat
user_shells:
  - bash
  - zsh
default_user_shell: zsh
bin_dirs:
  - "{{ binaries_prefix[ansible_distribution].path }}"
  - "$HOME/tools/bin"
  - "/usr/lib/go/bin"
  - "$HOME/workspace/gocode/bin"
  - "$HOME/.local/bin"
xsession_wm_choices:
  - awesome
  - i3
  - sawfish
  - stumpwm
  - xmonad
xsession_current_wm: "{{ xsession_wm_choices[3] }}"
stumpwm_config_path: "{{ ansible_env.HOME}}/.stumpwm.d"
