misc_paths:
  - { path: "{{ binaries_prefix[ansible_distribution].path }}",
      become: "{{ binaries_prefix[ansible_distribution].become | default(False) }}" }
  - { path: "{{ ansible_env.HOME }}/.gnupg", mode: '0700', become: yes }
  - { path: "{{ ansible_env.HOME }}/.imapfilter" }
  - { path: "{{ nixos_dotfiles_location }}/mail", become: yes, dists: ["NixOS"] }
  - { path: "{{ ansible_env.HOME }}/.ssh", mode: '0700', recurse: no }
  - { path: "{{ ansible_env.HOME }}/pids", become: yes, dists: ["Gentoo"] }
misc_templates:
  - { src: ".guile", dest: "{{ ansible_env.HOME }}/.guile", dists: ["Gentoo"] }
  - { src: ".guile", dest: "{{ nixos_dotfiles_location }}/.guile", become: yes, dists: ["NixOS"] }
  - { src: ".editorconfig", dest: "{{ workspace_path }}/.editorconfig", dists: ["Gentoo"] }
  - { src: ".editorconfig", dest: "{{ nixos_dotfiles_location }}/.editorconfig", become: yes, dists: ["NixOS"] }
  - { src: "gnupg/gpg-agent.conf", dest: "{{ ansible_env.HOME }}/.gnupg/gpg-agent.conf", mode: '0600', become: yes, dists: ["Gentoo"] }
  - { src: "gnupg/gpg.conf", dest: "{{ ansible_env.HOME }}/.gnupg/gpg.conf", mode: '0600', become: yes, dists: ["Gentoo"] }
  - { src: "mail/.mailcap", dest: "{{ ansible_env.HOME }}/.mailcap", dists: ["Gentoo"] }
  - { src: "mail/.mailcap", dest: "{{ nixos_dotfiles_location }}/.mailcap", become: yes, dists: ["NixOS"] }
  - { src: "mail/.mbsyncrc", dest: "{{ ansible_env.HOME }}/.mbsyncrc", dists: ["Gentoo"] }
  - { src: "mail/.mbsyncrc", dest: "{{ nixos_dotfiles_location }}/.mbsyncrc", become: yes, dists: ["NixOS"] }
  - { src: "mail/.msmtprc", dest: "{{ ansible_env.HOME }}/.msmtprc", dists: ["Gentoo"] }
  - { src: "mail/.msmtprc", dest: "{{ nixos_dotfiles_location }}/.msmtprc", become: yes, dists: ["NixOS"] }
  - { src: "mail/imapfilter.conf.lua", dest: "{{ ansible_env.HOME }}/.imapfilter/config.lua",
      handlers: ["services | imapfilter | restart service"], dists: ["Gentoo"] }
  - { src: "mail/imapfilter.conf.lua", dest: "{{ nixos_dotfiles_location }}/mail/imapfilter_config.lua", become: yes, dists: ["NixOS"] }
  - { src: "ssh_config", dest: "{{ ansible_env.HOME }}/.ssh/config" }
  - { src: "mpd.conf", dest: "/etc/mpd.conf", user: root, become: yes, dists: ["Gentoo"] }
  - { src: "mpd.conf", dest: "{{ nixos_dotfiles_location }}/mpd.conf", become: yes, dists: ["NixOS"] }
  - { src: "scripts/hddtemp", dest: "{{ binaries_prefix['Gentoo'].path }}/hddtemp",
      become: "{{ binaries_prefix['Gentoo'].become | default(False) }}", dists: ["Gentoo"] }
tmpfs_paths:
  - { path: "{{ ansible_env.HOME }}/.cache", uid: "1000", gid: "1000", size: "2G", mode: "0755"}
emacs_config_name_literal: "{{ emacs_config_dir }}/config.org"
emacs_config_name_tangled: "{{ emacs_config_dir }}/config.el"
email_creds_path: "{{ ansible_env.HOME }}/docs/enc/cred"
imapfilter_account_personal:
  address: "aaermolov@gmail.com"
  server: "imap.gmail.com"
  ssl: "tls"
  enabled: yes
imapfilter_daemon_opts:
  - { key: "-l", value: "{{ ansible_env.HOME }}/imapfilter.log" }
  - { key: "-d", value: "{{ ansible_env.HOME }}/imapfilter.debug" }
  - { key: "-v"}
thd_tmp_dir: "/tmp/thd"
tg_backup_formatter: plaintext
tg_backup_base_dir: "/telegram-logs/tg_logs"
tg_backup_kill_tg: yes
tg_cli_port: 9009
