private_hosts_data: "{{ lookup('file', '{{ playbook_dir }}/../private/work_hosts') }}"
user_name: octocat
user_group: octocat
emacs_config_name_literal: "{{ emacs_config_dir }}/config.org"
emacs_config_name_tangled: "{{ emacs_config_dir }}/config.el"
