private_hosts_data: "{{ lookup('file', '{{ playbook_dir }}/../private/work_hosts') }}"
user_name: octocat
user_group: octocat
emacs_config_name_literal: "{{ emacs_config_dir }}/config.org"
emacs_config_name_tangled: "{{ emacs_config_dir }}/config.el"
ffdc_traits: { clone_from: "https://github.com/Unode/firefox_decrypt", local_path: "/tmp/firefox_decrypt" }
email_creds_path: "{{ ansible_env.HOME }}/docs/enc/cred"
imapfilter_accounts:
  - { name: "personal", address: "aaermolov@gmail.com", server: "imap.gmail.com", ssl: "ssl3", enabled: yes }
