workspace_path: "{{ ansible_env.HOME }}/workspace"
virtualenvs_subdir: ".virtualenvs"
system_dirs:
  - "/etc/X11/xorg.conf.d"
  - "/etc/acpi"
  - "/etc/acpi/actions"
  - "/etc/acpi/events"
  - "/etc/udev/rules.d"
  - "/usr/share/genkernel/defaults"
homedir_subdirs:
  - ".config/dunst"
  - ".config/i3"
  - ".config/rofi"
  - ".config/twmn"
  - ".gnupg"
  - ".imapfilter"
  - ".local/share/applications"
  - ".sawfish"
  - ".ssh"
  - ".tmux/plugins"
  - ".zsh"
  - "{{ virtualenvs_subdir }}"
  - "{{ workspace_path }}/python"
