shell_paths:
  - { path: "{{ ansible_env.HOME }}/.tmux/plugins", recurse: no, dists: ["Gentoo"] }
  - { path: "{{ zsh_subconfig_path }}/completion", dists: ["Gentoo"] }
  - { path: "{{ nixos_dotfiles_location }}/shell", become: yes, dists: ["NixOS"] }
shell_templates:
  - { src: ".tmux.conf", dest: "{{ ansible_env.HOME }}/.tmux.conf", dists: ["Gentoo"] }
  - { src: ".tmux.conf", dest: "{{ nixos_dotfiles_location }}/shell/tmux.conf", dists: ["NixOS"] } # TODO: think of generating Nix substitutions here
  - { src: ".urlview", dest: "{{ ansible_env.HOME }}/.urlview" }
  - { src: "shell/.zshrc.j2", dest: "{{ ansible_env.HOME }}/.zshrc", dists: ["Gentoo"] }
  - { src: "shell/.zshrc.j2", dest: "{{ nixos_dotfiles_location }}/shell/.zshrc", become: yes, dists: ["NixOS"] } # NOTE: will not be used as is and generated just for reference
  - { src: "shell/aliases.zsh", dest: "{{ zsh_subconfig_path }}/aliases.zsh", dists: ["Gentoo"] }
  - { src: "shell/functions.zsh", dest: "{{ zsh_subconfig_path }}/functions.zsh", dists: ["Gentoo"] }
  - { src: "shell/functions.zsh", dest: "{{ nixos_dotfiles_location }}/shell/functions.zsh", become: yes, dists: ["NixOS"] }
  - { src: "scripts/status_bat_info", dest: "{{ binaries_prefix[ansible_distribution].path }}/status_bat_info", dists: ["Gentoo"] }
  - { src: "scripts/status_cpu_temp", dest: "{{ binaries_prefix[ansible_distribution].path }}/status_cpu_temp", dists: ["Gentoo"] }
  - { src: "scripts/status_uptime", dest: "{{ binaries_prefix[ansible_distribution].path }}/status_uptime", dists: ["Gentoo"] }
  - { src: "scripts/statusbar", dest: "{{ binaries_prefix[ansible_distribution].path }}/statusbar", dists: ["Gentoo"] }
  - { src: "scripts/update-portage-metadata", dest: "{{ binaries_prefix[ansible_distribution].path }}/update-portage-metadata", dists: ["Gentoo"] }
  - { src: "scripts/portage-check-world", dest: "{{ binaries_prefix[ansible_distribution].path }}/portage-check-world", dists: ["Gentoo"] }
  - { src: "shell/common_settings.j2", dest: "{{ ansible_env.HOME }}/common_settings", dists: ["Gentoo"] }
  - { src: "shell/common_settings.j2", dest: "{{ nixos_dotfiles_location }}/shell/common_settings", become: yes, dists: ["NixOS"] } # NOTE: will not be used as is and generated just for reference
  - { src: "shell/common_settings_bash.j2", dest: "{{ ansible_env.HOME }}/common_settings_bash", dists: ["Gentoo"] }
  - { src: "shell/common_settings_bash.j2", dest: "{{ nixos_dotfiles_location }}/shell/common_settings_bash", become: yes, dists: ["NixOS"] } # NOTE: will not be used as is and generated just for reference
  - { src: "shell/zsh.plugins.j2", dest: "{{ zsh_plugins_list_location }}", dists: ["Gentoo"] }
  - { src: "shell/tmux-sessions.j2", dest: "{{ ansible_env.HOME }}/tmux-sessions" }
default_user_name: octocat
default_user_groups:
  - bumblebee
  - docker
  - libvirt
  - plugdev
  - scanner
  - vboxusers
  - video
  - input
  - wheel
  - wireshark
common_settings_basenames:
  - common_settings
  - common_settings_bash
virtualenvs_subdir: ".virtualenvs"
workspace_path: "{{ ansible_env.HOME }}/workspace"
zsh_extension_dirs:
  - "$HOME/.zsh/completion"
export_variables:
  - { name: "GREP_OPTIONS", value: "--color=auto" }
  - { name: "GREP_COLOR", value: "'1;32'" }
  - { name: "SHELL", value: "/bin/bash" }
  - { name: "GOROOT", value: "/usr/lib/go" }
  - { name: "GOPATH", value: "$HOME/workspace/gocode" }
  - { name: "XAUTHORITY", value: "$HOME/.Xauthority" }
  - { name: "FZF_MARKS_FILE", value: "{{ shell_bookmarks_file }}" }
  - { name: "GTAGSLIBPATH", value: "$HOME/.gtags/" }
  - { name: "FZF_ZSH", value: "/usr/share/zsh/site-contrib/fzf.zsh" }
  - { name: "CURRENT_WM", value: "{{ xsession_current_wm }}" }
  - { name: "WORKON_HOME", value: "$HOME/{{ virtualenvs_subdir }}" }
  - { name: "PROJECT_HOME", value: "{{ workspace_path }}/python" }
  - { name: "PROJECTS", value: "{{ workspace_path }}/foss" }
editor_choices:
  - "emacsclient"
  - "vim"
  - "vi"
tmux_predefined_sessions:
  - { name: "work", initial_app: "mc" }
  - { name: "housekeeping" }
  - { name: "self", initial_app: "mc" }
default_tmux_session: "{{ tmux_predefined_sessions[-1] }}"
zsh_plugins:
  - b4b4r07/enhancd
  - marzocchi/zsh-notify
  - urbainvaes/fzf-marks
  - zsh-users/zsh-syntax-highlighting
  - zsh-users/zaw
  - voronkovich/project.plugin.zsh
  - mafredri/zsh-async
  - wiedzmin/zsh-fuzzy-search-and-edit
  - unixorn/git-extra-commands
  - RobSis/zsh-reentry-hook
  - ninrod/pass-zsh-completion
  - wiedzmin/browse-commit
  - mgee/slimline
zsh_plugins_list_location: "{{ zsh_subconfig_path }}/plugins.list"
zsh_plugins_antibody_script: "{{ zsh_subconfig_path }}/plugins.sh"
zsh_plugins_antibody_cache_dir: "{{ ansible_env.HOME}}/.cache/antibody"
zsh_plugins_antibody_bundle_command: "antibody bundle < {{ zsh_plugins_list_location }} > {{ zsh_plugins_antibody_script }}"
