---

system_paths:
  - { path: "/etc/acpi/actions", mode: '0700', user: root, become: yes, dists: ["Gentoo"] }
  - { path: "/etc/acpi/events", mode: '0700', user: root, become: yes, dists: ["Gentoo"] }
  - { path: "/etc/udev/rules.d", mode: '0644', user: root, become: yes, dists: ["Gentoo"] }
  - { path: "/etc/X11/xorg.conf.d", mode: '0644', user: root, become: yes, dists: ["Gentoo"] }
system_templates:
  - { src: "acpi/events/battery", dest: "/etc/acpi/events/battery", mode: '0755', user: root, become: yes, dists: ["Gentoo"] }
  - { src: "acpi/events/default", dest: "/etc/acpi/events/default", mode: '0755', user: root, become: yes, dists: ["Gentoo"] }
  - { src: "acpi/events/lid", dest: "/etc/acpi/events/lid", mode: '0755', user: root, become: yes, dists: ["Gentoo"] }
  - { src: "acpi/events/power", dest: "/etc/acpi/events/power", mode: '0755', user: root, become: yes, dists: ["Gentoo"] }
  - { src: "acpi/events/sleep", dest: "/etc/acpi/events/sleep", mode: '0755', user: root, become: yes, dists: ["Gentoo"] }
  - { src: "acpi/events/thinkpad-dock", dest: "/etc/acpi/events/thinkpad-dock", mode: '0755', user: root, become: yes, dists: ["Gentoo"] }
  - { src: "acpi/events/thinkpad-undock", dest: "/etc/acpi/events/thinkpad-undock", mode: '0755', user: root, become: yes, dists: ["Gentoo"] }
  - { src: "acpi/actions/default.sh", dest: "/etc/acpi/actions/default.sh", mode: '0755', user: root, become: yes, dists: ["Gentoo"] }
  - { src: "acpi/actions/lid.sh", dest: "/etc/acpi/actions/lid.sh", mode: '0755', user: root, become: yes, dists: ["Gentoo"] }
  - { src: "acpi/actions/power.sh", dest: "/etc/acpi/actions/power.sh", mode: '0755', user: root, become: yes, dists: ["Gentoo"] }
  - { src: "acpi/actions/powerbtn.sh", dest: "/etc/acpi/actions/powerbtn.sh", mode: '0755', user: root, become: yes, dists: ["Gentoo"] }
  - { src: "acpi/actions/sleep.sh", dest: "/etc/acpi/actions/sleep.sh", mode: '0755', user: root, become: yes, dists: ["Gentoo"] }
  - { src: "acpi/actions/thinkpad-dock.sh", dest: "/etc/acpi/actions/thinkpad-dock.sh", mode: '0755', user: root, become: yes, dists: ["Gentoo"] }
  - { src: "acpi/actions/thinkpad-undock.sh", dest: "/etc/acpi/actions/thinkpad-undock.sh", mode: '0755', user: root, become: yes, dists: ["Gentoo"] }
  - { src: "xorg.conf.d/10-input.conf", dest: "/etc/X11/xorg.conf.d/10-input.conf", mode: '0755', user: root, become: yes, dists: ["Gentoo"] }
  - { src: "xorg.conf.d/15-synaptics.conf", dest: "/etc/X11/xorg.conf.d/15-synaptics.conf", mode: '0755', user: root, become: yes, dists: ["Gentoo"] }
  - { src: "xorg.conf.d/17-intel-modesetting.conf", dest: "/etc/X11/xorg.conf.d/17-intel-modesetting.conf", mode: '0755', user: root, become: yes, dists: ["Gentoo"] }
  - { src: "xorg.conf.d/20-opengl.conf", dest: "/etc/X11/xorg.conf.d/20-opengl.conf", mode: '0755', user: root, become: yes, dists: ["Gentoo"] }
  - { src: "system/rc.conf", dest: "/etc/rc.conf", mode: '0755', user: root, become: yes, dists: ["Gentoo"] }
system_xorg_synaptics_options:
  - { name: "CircScrollTrigger", value: "1" }
  - { name: "CircularScrolling", value: "on" }
  - { name: "CoastingSpeed", value: "0" }
  - { name: "EmulateTwoFingerMinW", value: "8" }
  - { name: "EmulateTwoFingerMinZ", value: "40" }
  - { name: "FingerHigh", value: "55" }
  - { name: "FingerLow", value: "35" }
  - { name: "HorizScrollDelta", value: "-111" }
  - { name: "HorizTwoFingerScroll", value: "on" }
  - { name: "PalmDetect", value: "1" }
  - { name: "PalmMinWidth", value: "8" }
  - { name: "PalmMinZ", value: "100" }
  - { name: "TapButton1", value: "1" }
  - { name: "TapButton3", value: "3" }
  - { name: "VertScrollDelta", value: "-111" }
  - { name: "VertTwoFingerScroll", value: "on" }
system_xorg_kbd_options:
  - { name: "SendCoreEvents", value: "true" }
  - { name: "XkbRules", value: "xorg" }
  - { name: "XkbModel", value: "pc104" }
  - { name: "XkbLayout", value: "us,ru" }
  - { name: "XkbVariant", value: ",winkeys" }
  - { name: "XkbOptions", value: "caps:none,compose:ralt" }
system_services:
  - { name: "NetworkManager", runlevel: "default", status: "started" }
  - { name: "acpid", runlevel: "default", status: "started" }
  - { name: "alsasound", runlevel: "default", status: "started" }
  - { name: "binfmt", runlevel: "boot", status: "started" }
  - { name: "bitlbee", runlevel: "default", status: "started" }
  - { name: "bootmisc", runlevel: "boot", status: "started" }
  - { name: "cgroups", runlevel: "sysinit", status: "started" }
  - { name: "consolefont", runlevel: "boot", status: "started" }
  - { name: "consolekit", runlevel: "default", status: "started" }
  - { name: "cupsd", runlevel: "default", status: "started" }
  - { name: "devfs", runlevel: "sysinit", status: "started" }
  - { name: "dmesg", runlevel: "sysinit", status: "started" }
  - { name: "docker", runlevel: "default", status: "started" }
  - { name: "fsck", runlevel: "boot", status: "started" }
  - { name: "hddtemp", runlevel: "default", status: "started" }
  - { name: "hibernate-cleanup", runlevel: "boot", status: "started" }
  - { name: "hostname", runlevel: "boot", status: "started" }
  - { name: "hwclock", runlevel: "boot", status: "started" }
  - { name: "keymaps", runlevel: "boot", status: "started" }
  - { name: "kmod-static-nodes", runlevel: "sysinit", status: "started" }
  - { name: "libvirtd", runlevel: "default", status: "started" }
  - { name: "local", runlevel: "default", status: "started" }
  - { name: "local", runlevel: "nonetwork", status: "started" }
  - { name: "localmount", runlevel: "boot", status: "started" }
  - { name: "loopback", runlevel: "boot", status: "started" }
  - { name: "modules", runlevel: "boot", status: "started" }
  - { name: "mpd", runlevel: "default", status: "started" }
  - { name: "mtab", runlevel: "boot", status: "started" }
  - { name: "netmount", runlevel: "default", status: "started" }
  - { name: "ntpd", runlevel: "default", status: "started" }
  - { name: "opentmpfiles-dev", runlevel: "sysinit", status: "started" }
  - { name: "opentmpfiles-setup", runlevel: "boot", status: "started" }
  - { name: "procfs", runlevel: "boot", status: "started" }
  - { name: "root", runlevel: "boot", status: "started" }
  - { name: "rpc.statd", runlevel:  "default", status: "started" }
  - { name: "shepherd", runlevel: "default", status: "started" } # !!! think of clashing with custom service initialization here in playbooks
  - { name: "smartd", runlevel: "default", status: "started" }
  - { name: "sshd", runlevel: "default", status: "started" }
  - { name: "swap", runlevel: "boot", status: "started" }
  - { name: "sysctl", runlevel: "boot", status: "started" }
  - { name: "sysfs", runlevel: "sysinit", status: "started" }
  - { name: "syslog-ng", runlevel: "default", status: "started" }
  - { name: "sysstat", runlevel: "default", status: "started" }
  - { name: "termencoding", runlevel: "boot", status: "started" }
  - { name: "tlsdate", runlevel: "default", status: "started" }
  - { name: "udev", runlevel: "sysinit", status: "started" }
  - { name: "udev-trigger", runlevel: "sysinit", status: "started" }
  - { name: "urandom", runlevel: "boot", status: "started" }
  - { name: "vixie-cron", runlevel: "default", status: "started" }
  - { name: "xdm", runlevel: "default", status: "started" }
  - { name: "nix-daemon", runlevel: "default", status: "started" }
