x11_paths:
  - { path: "{{ home_config_path }}/dunst"}
  - { path: "{{ home_config_path }}/i3"}
  - { path: "{{ home_config_path }}/rofi"}
  - { path: "{{ home_config_path }}/twmn"}
  - { path: "{{ ansible_env.HOME }}/.local/share/applications"}
  - { path: "{{ ansible_env.HOME }}/.sawfish"}
x11_templates:
  - { src: "browser/.surfingkeysrc", dest: "{{ ansible_env.HOME }}/.surfingkeysrc" }
  - { src: "x11/dunstrc.template", dest: "{{ home_config_path }}/dunst/dunstrc" }
  - { src: "x11/rofi.j2", dest: "{{ home_config_path }}/rofi/config" }
  - { src: "x11/oxide.rasi", dest: "{{ home_config_path }}/rofi/oxide.rasi" }
  - { src: "categorize.cfg", dest: "{{ ansible_env.HOME }}/.arbtt/categorize.cfg" }
  - { src: ".gmrunrc", dest: "{{ ansible_env.HOME }}/.gmrunrc" }
  - { src: ".i3status.conf", dest: "{{ ansible_env.HOME }}/.i3status.conf" }
  - { src: ".sawfishrc", dest: "{{ ansible_env.HOME }}/.sawfish/rc" }
  - { src: ".stalonetrayrc", dest: "{{ ansible_env.HOME }}/.stalonetrayrc" }
  - { src: ".xxkbrc", dest: "{{ ansible_env.HOME }}/.xxkbrc" }
  - { src: "i3.conf", dest: "{{ home_config_path }}/i3/config" }
  - { src: "twmn.conf", dest: "{{ home_config_path }}/twmn/twmn.conf" }
  - { src: "xmobarrc", dest: "{{ ansible_env.HOME }}/.xmonad/xmobarrc" }
  - { src: "xmobarrc-noinet", dest: "{{ ansible_env.HOME }}/.xmonad/xmobarrc-noinet" }
  - { src: "xmobarrc.xmonad.old", dest: "{{ ansible_env.HOME }}/.xmonad/xmobarrc.xmonad.old" }
  - { src: "emacsclient.desktop", dest: "{{ ansible_env.HOME }}/.local/share/applications/emacsclient.desktop" }
  - { src: "resources/.Xresources.template", dest: "{{ ansible_env.HOME }}/.Xresources", xresources: yes }
  - { src: "resources/.urxvtrc.template", dest: "{{ ansible_env.HOME }}/.urxvtrc", enabled: yes, xresources: yes }
  - { src: "resources/.xftrc.template", dest: "{{ ansible_env.HOME }}/.xftrc", enabled: yes, xresources: yes }
  - { src: "resources/.emacsrc.template", dest: "{{ ansible_env.HOME }}/.emacsrc", enabled: yes, xresources: yes }
mime_assocs:
  - { program: "abiword", mimetype: "application/msword" }
  - { program: "{{ default_image_viewer_executable }}", mimetype: "image/jpeg" }
  - { program: "{{ default_image_viewer_executable }}", mimetype: "image/png" }
  - { program: "{{ default_browser_executable }}", mimetype: "text/html" }
  - { program: "{{ default_video_player_executable }}", mimetype: "video/avi" }
  - { program: "{{ default_video_player_executable }}", mimetype: "video/mp4" }
  - { program: "{{ default_video_player_executable }}", mimetype: "video/mpeg" }
  - { program: "{{ default_video_player_executable }}", mimetype: "video/x-flv" }
  - { program: "{{ default_video_player_executable }}", mimetype: "video/x-matroska" }
  - { program: "{{ default_video_player_executable }}", mimetype: "video/x-ms-wmv" }
  - { program: "{{ default_ebook_viewer_executable }}", mimetype: "application/pdf" }
  - { program: "{{ default_ebook_viewer_executable }}", mimetype: "application/x-pdf" }
  - { program: "{{ default_ebook_viewer_executable }}", mimetype: "image/vnd.djvu" }
  - { program: "{{ default_ebook_viewer_executable }}", mimetype: "image/x-djvu" }
vpn_service_name: job-vpn
osd_delay: 2
osd_font: "-*-fixed-*-*-*-*-24-*-*-*-*-*-*-*"
osd_color: green
osd_x_offset_1: 1000
osd_y_offset_1: 600
osd_x_offset_2: 1400
osd_y_offset_2: 1000
cpu_usage_interval: 0.1
xrandr_vga_output: VGA-1
xrandr_internal_output: LVDS-1
xrandr_vga_rotation: left
xrandr_dock_left_output: HDMI-2
xrandr_dock_left_rotation: normal
xrandr_dock_right_output: HDMI-3
xrandr_dock_right_rotation: left
xrandr_blue: 0.5
xrandr_brightness: 0.7
x11_stumpwm_traits: { clone_from: "https://github.com/wiedzmin/stumpwm", local_path: "{{ ansible_env.HOME }}/.commonlisp/stumpwm-git" }
x11_stumpwm_set_font: yes
xsession_wallpaper_location: "{{ ansible_env.HOME }}/blobs/wallpaper"
xsession_wallpaper_file: "{{ xsession_wallpaper_location }}/alena-aenami-7p-m-1k.jpg"
xsession_loop_wm: no
xsession_errorlogs_to_keep: 3
xsession_services:
  - { command: "arbtt-capture", enabled: yes, heavyweight: no }
  - { command: "autocutsel -buttonup", enabled: yes, heavyweight: no }
  - { command: "dbus-daemon --session", enabled: yes, heavyweight: no }
  - { command: "dropbox", enabled: yes, heavyweight: yes }
  - { command: "kbdd", enabled: "{{ xsession_current_wm not in ['stumpwm', 'xmonad'] }}", heavyweight: no }
  - { command: "nm-applet", enabled: yes, heavyweight: no }
  - { command: "pulseaudio --start", enabled: yes, heavyweight: no }
  - { command: "rdm", enabled: yes, heavyweight: no }
  - { command: "redshift -l 55.751244:37.618423 -t 5500:3700 -m randr", enabled: yes, heavyweight: no }
  - { command: "trayer-srg --edge top --align right --monitor primary --SetDockType true --SetPartialStrut true --expand true --widthtype request --height 15 --transparent true --tint 0x000000",
  enabled: "{{ xsession_current_wm not in ['awesome', 'stumpwm'] }}",
  heavyweight: no }
  - { command: "unclutter -idle 5", enabled: yes, heavyweight: no }
  - { command: "volumeicon", enabled: no, heavyweight: no }
  - { command: "xxkb", enabled: "{{ xsession_current_wm not in ['awesome', 'stumpwm'] }}", heavyweight: no }
xsession_disable_capslock: yes
xsession_timezone: Europe/Moscow
xsession_media_mount: yes
