x11_templated_configs:
  - { src: "x11/dunstrc.template", dest: ".config/dunst/dunstrc" }
x11_resources_configs:
  - { src: "resources/.Xresources.template", dest: ".Xresources" }
  - { src: "resources/.urxvtrc.template", dest: ".urxvtrc", enabled: yes }
  - { src: "resources/.xftrc.template", dest: ".xftrc", enabled: yes }
  - { src: "resources/.emacsrc.template", dest: ".emacsrc", enabled: yes }
mime_assocs:
  - { program: "abiword", mimetype: "application/msword" }
  - { program: "feh", mimetype: "image/jpeg" }
  - { program: "feh", mimetype: "image/png" }
  - { program: "{{ default_browser_executable }}", mimetype: "text/html" }
  - { program: "vlc", mimetype: "video/avi" }
  - { program: "vlc", mimetype: "video/mp4" }
  - { program: "vlc", mimetype: "video/mpeg" }
  - { program: "vlc", mimetype: "video/x-flv" }
  - { program: "vlc", mimetype: "video/x-matroska" }
  - { program: "vlc", mimetype: "video/x-ms-wmv" }
  - { program: "zathura", mimetype: "application/pdf" }
  - { program: "zathura", mimetype: "application/x-pdf" }
  - { program: "zathura", mimetype: "image/vnd.djvu" }
  - { program: "zathura", mimetype: "image/x-djvu" }
vpn_service_name: job-vpn
osd_delay: 2
osd_font: "-*-fixed-*-*-*-*-24-*-*-*-*-*-*-*"
osd_color: green
osd_x_offset_1: 1000
osd_y_offset_1: 600
osd_x_offset_2: 1400
osd_y_offset_2: 1000
cpu_usage_interval: 0.1
xrandr_vga_output: VGA-1
xrandr_internal_output: LVDS-1
xrandr_vga_rotation: left
xrandr_dock_left_output: HDMI-2
xrandr_dock_left_rotation: normal
xrandr_dock_right_output: HDMI-3
xrandr_dock_right_rotation: left
xrandr_blue: 0.5
xrandr_brightness: 0.7
x11_stumpwm_traits: { clone_from: "https://github.com/wiedzmin/stumpwm", local_path: "/tmp/stumpwm-git" }
xsession_wallpaper_location: "{{ ansible_env.HOME }}/blobs/wallpaper"
xsession_wallpaper_file: "{{ xsession_wallpaper_location }}/alena-aenami-7p-m-1k.jpg"
xsession_loop_wm: no
xsession_errorlogs_to_keep: 3
# TODO automate xsession_{lvds, ext}_width retrieving using facts
xsession_services:
  - { command: "arbtt-capture", enabled: yes, heavyweight: no }
  - { command: "autocutsel -buttonup", enabled: yes, heavyweight: no }
  - { command: "dbus-daemon --session", enabled: yes, heavyweight: no }
  - { command: "dropbox", enabled: yes, heavyweight: yes }
  - { command: "kbdd", enabled: "{{ xsession_current_wm not in ['stumpwm', 'xmonad'] }}", heavyweight: no }
  - { command: "nm-applet", enabled: yes, heavyweight: no }
  - { command: "pulseaudio --start", enabled: yes, heavyweight: no }
  - { command: "rdm", enabled: yes, heavyweight: no }
  - { command: "redshift -l 55.751244:37.618423 -t 5500:3700 -m randr", enabled: yes, heavyweight: no }
  - { command: "trayer-srg --edge top --align right --monitor primary --SetDockType true --SetPartialStrut true --expand true --widthtype request --height 15 --transparent true --tint 0x000000",
  enabled: "{{ xsession_current_wm not in ['awesome', 'stumpwm'] }}",
  heavyweight: no } # TODO: try to check against xsession_current_wm (enable in all but awesome and maybe some others)
  - { command: "unclutter -idle 5", enabled: yes, heavyweight: no }
  - { command: "volumeicon", enabled: no, heavyweight: no }
  - { command: "xxkb", enabled: "{{ xsession_current_wm not in ['awesome', 'stumpwm'] }}", heavyweight: no } # TODO: try to check against xsession_current_wm (enable in all but awesome and maybe some others)
xsession_disable_capslock: yes
xsession_timezone: Europe/Moscow
xsession_media_mount: yes
