x11_system_dirs:
  - "/etc/X11/xorg.conf.d"
x11_homedir_subdirs:
  - ".config/dunst"
  - ".config/i3"
  - ".config/rofi"
  - ".config/twmn"
  - ".local/share/applications"
  - ".sawfish"
x11_system_files:
  - { src: "xorg.conf.d/20opengl.conf", dest: "/etc/X11/xorg.conf.d/20opengl.conf" }
  - { src: "xorg.conf.d/input.conf", dest: "/etc/X11/xorg.conf.d/input.conf" }
  - { src: "xorg.conf.d/synaptics.conf", dest: "/etc/X11/xorg.conf.d/synaptics.conf" }
x11_homedir_files:
  - { src: ".gmrunrc", dest: ".gmrunrc" }
  - { src: ".i3status.conf", dest: ".i3status.conf" }
  - { src: ".sawfishrc", dest: ".sawfish/rc" }
  - { src: ".stalonetrayrc", dest: ".stalonetrayrc" }
  - { src: ".xxkbrc", dest: ".xxkbrc" }
  - { src: "browser/.pentadactylrc", dest: ".pentadactylrc" }
  - { src: "categorize.cfg", dest: ".arbtt/categorize.cfg" }
  - { src: "i3.conf", dest: ".config/i3/config" }
  - { src: "rofi.conf", dest: ".config/rofi/config" }
  - { src: "twmn.conf", dest: ".config/twmn/twmn.conf" }
  - { src: "xmobarrc", dest: ".xmonad/xmobarrc" } # TODO: abstract away
  - { src: "xmobarrc-noinet", dest: ".xmonad/xmobarrc-noinet" } # TODO: abstract away
  - { src: "xmobarrc.xmonad.old", dest: ".xmonad/xmobarrc.xmonad.old" } # TODO: abstract away
  - { src: "emacsclient.desktop", dest: ".local/share/applications/emacsclient.desktop" }
x11_templated_configs:
  - { src: "x11/dunstrc.template", dest: ".config/dunst/dunstrc" }
mime_assocs:
  - { program: "abiword", mimetype: "application/msword" }
  - { program: "feh", mimetype: "image/jpeg" }
  - { program: "feh", mimetype: "image/png" }
  - { program: "{{ default_browser_executable }}", mimetype: "text/html" }
  - { program: "vlc", mimetype: "video/avi" }
  - { program: "vlc", mimetype: "video/mp4" }
  - { program: "vlc", mimetype: "video/mpeg" }
  - { program: "vlc", mimetype: "video/x-flv" }
  - { program: "vlc", mimetype: "video/x-matroska" }
  - { program: "vlc", mimetype: "video/x-ms-wmv" }
  - { program: "zathura", mimetype: "application/pdf" }
  - { program: "zathura", mimetype: "application/x-pdf" }
  - { program: "zathura", mimetype: "image/vnd.djvu" }
  - { program: "zathura", mimetype: "image/x-djvu" }
osd_delay: 2
osd_font: "-*-fixed-*-*-*-*-24-*-*-*-*-*-*-*"
osd_color: green
osd_x_offset_1: 1000
osd_y_offset_1: 600
osd_x_offset_2: 1400
osd_y_offset_2: 1000
cpu_usage_interval: 0.1
xrandr_vga_output: VGA1
xrandr_internal_output: LVDS1
xrandr_vga_rotation: left
xrandr_dock_left_output: HDMI2
xrandr_dock_left_rotation: normal
xrandr_dock_right_output: VGA1
xrandr_dock_right_rotation: left
