---

- name: gpg | get private key ID
  tags: [common]
  shell: "gpg2 --list-secret-keys --keyid-format LONG {{ gnupg_key_id }} | grep sec | cut -d' ' -f 4 | cut -d'/' -f 2"
  register: gpg_private_key_id

- name: facts | gpg private key id
  tags: [common]
  set_fact:
    gpg_private_key_id: "{{ gpg_private_key_id.stdout }}"

- name: groups | current user primary group
  tags: [common]
  shell: "groups | cut -d' ' -f1"
  register: current_user_primary_group

- name: facts | current user primary group
  tags: [common]
  set_fact:
    current_user_primary_group: "{{ current_user_primary_group.stdout }}"
