---

- include_vars: fs.yml
  tags: [always]

- name: copy homedir files
  tags: [fs]
  copy:
    content: "{{ lookup('template', item.src) }}"
    dest: "{{ ansible_env.HOME }}/{{ item.dest }}"
    mode: 0755
  with_items: "{{ dev_homedir_files }}"

- name: copy custom scripts
  tags: [fs, scripts]
  copy:
    content: "{{ lookup('template', 'scripts/{{ item | basename }}') }}"
    dest: "{{ local_binaries_prefix }}/{{ item | basename }}"
    mode: 0755
  with_fileglob:
    - "{{ role_path }}/templates/scripts/*"
  become: yes
