---

- include_vars: fs.yml
  tags: [fs]

- name: ensure some dirs exist
  tags: [fs]
  file:
    path: "{{ item.path }}"
    state: directory
    mode: "{{ item.mode }}"
    owner: "{{ user_name }}"
    group: "{{ user_group }}"
    recurse: "{{ item.recurse }}"
  become: yes
  with_items: "{{ dev_dirs }}"

- name: ensure home subdirs exist
  tags: [fs]
  file:
    path: "{{ ansible_env.HOME }}/{{ item }}"
    state: directory
  with_items: "{{ dev_homedir_subdirs }}"

- name: copy homedir files
  tags: [fs]
  copy:
    content: "{{ lookup('template', item.src) }}"
    dest: "{{ ansible_env.HOME }}/{{ item.dest }}"
    mode: 0755
  with_items: "{{ dev_homedir_files }}"

- name: copy custom scripts
  tags: [fs, scripts]
  copy:
    content: "{{ lookup('template', 'scripts/{{ item | basename }}') }}"
    dest: "{{ local_binaries_prefix }}/{{ item | basename }}"
    mode: 0755
  with_fileglob:
    - "{{ role_path }}/templates/scripts/*"
  become: yes
