---

- include_vars: golang.yml
  tags: [always]

- name: setup gometalinter
  tags: [golang]
  shell: gometalinter --install --update
  with_first_found:
    - files:
        - gometalinter
      paths:
        - "{{ golang_bin_path }}"
