---

- name: allow Docker to connect to local X server
  shell: xhost +local:dockerfile

# DISCLAIMER: at the moment all started containers are planned to stop/remove manually

- name: start Zeal viewer
  docker_container:
    name: zeal
    image: wusuopu/zealdocs:{{ zeal_version }}
    state: started
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"
      - "{{ zeal_cache }}:/root/.cache/Zeal/Zeal"
      - "{{ zeal_docsets }}:/root/.local/share/Zeal/Zeal"
    env:
      DISPLAY: ":0"
  tags:
    - zeal
