---

- name: register current time
  shell: "date +%Y%m%d%H%M%S"
  register: current_run_timestamp
  tags:
    - always

- name: allow Docker to connect to local X server
  shell: xhost +local:dockerfile

# DISCLAIMER: at the moment most of started containers are planned to stop/remove manually

- name: start Zeal viewer
  docker_container:
    name: zeal
    image: wusuopu/zealdocs:{{ zeal_version }}
    state: started
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"
      - "{{ zeal_cache }}:/root/.cache/Zeal/Zeal"
      - "{{ zeal_docsets }}:/root/.local/share/Zeal/Zeal"
    env:
      DISPLAY: ":0"
  tags:
    - zeal

- name: start devdns
  docker_container:
    name: devdns
    image: ruudud/devdns
    state: started
    expose:
      - 53:53/udp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  tags:
    - devdns_start

- name: setup devdns host <-> containers resolving
  blockinfile:
    path: /etc/dhcp/dhclient.conf
    block: |
      supersede domain-name "dev";
      prepend domain-name-servers 127.0.0.1;
  become: yes
  tags:
    - devdns_start

- name: stop devdns container
  docker_container:
    name: devdns
    state: stopped
  tags:
    - devdns_stop

- name: remove devdns host <-> containers resolving
  blockinfile:
    path: /etc/dhcp/dhclient.conf
    block: |
      supersede domain-name "dev";
      prepend domain-name-servers 127.0.0.1;
    state: absent
  become: yes
  tags:
    - devdns_stop

- name: THD | prepare temporary dir
  copy:
    src: "{{ item.src }}/"
    dest: "{{ item.dest }}"
    mode: 0755
  with_items:
    - { src: "{{ role_path }}/files/thd", dest: "{{ thd_tmp_dir }}" }
    - { src: "{{ playbook_dir }}/../private/telegram", dest: "{{ thd_tmp_dir }}/private"}
  tags:
    - thd

- name: THD | update config
  copy:
    content: "{{ lookup('template', 'thd_config.template') }}"
    dest: "{{ thd_tmp_dir }}/thd_config.yaml"
    mode: 0755
  tags:
    - thd

- name: THD | start service
  docker_service:
    project_src: "{{ thd_tmp_dir }}"
    build: yes
  tags:
    - thd
