project_root_rel: "{{ playbook_dir }}/.."
project_root: "{{ project_root_rel | realpath }}"
pids_dir: "{{ ansible_env.HOME }}/pids"
buildapp_repo_location: /tmp/buildapp
ripgrep_repo_location: /tmp/ripgrep
gqs_repo_location: /tmp/git-quick-stats
addrlookup_repo_location: /tmp/notmuch-addrlookup-c
tmuxifier_repo_location: "{{ ansible_env.HOME }}/.tmuxifier"
zshnip_repo_location: /tmp/zshnip
mail_configs_dir: "{{ project_root }}/conf.d/user/mail"
imapfilter_d_path: "{{ mail_configs_dir }}/imapfilter.d"
imapfilter_config: "{{ mail_configs_dir }}/imapfilter-config.lua"
openrc_services_list:
  - shepherd
  - job-vpn
  - sshuttle
system_dirs:
  - '/etc/X11'
  - '/etc/conf.d'
  - '/etc/portage'
entries_to_symlinks:
  - '/etc/acpi'
  - '/etc/X11/xorg.conf.d'
  - '/etc/conf.d/docker'
  - '/etc/mpd.conf'
  - '/etc/portage/package.mask'
  - '/etc/portage/package.use'
  - '/etc/portage/repos.conf'
  - '/etc/portage/make.conf'
  - '/etc/portage/package.accept_keywords'
  - '/etc/portage/package.keywords'
  - '/etc/portage/package.license'
  - '/etc/portage/package.unmask'
system_symlinks:
  - { src: 'conf.d/system/acpi', dest: '/etc/acpi' }
  - { src: 'conf.d/X11/xorg.conf.d', dest: '/etc/X11/xorg.conf.d' }
  - { src: 'conf.d/system/docker', dest: '/etc/conf.d/docker' }
  - { src: 'conf.d/system/mpd.conf', dest: '/etc/mpd.conf' }
  - { src: 'conf.d/system/portage/package.mask', dest: '/etc/portage/package.mask' }
  - { src: 'conf.d/system/portage/package.use', dest: '/etc/portage/package.use' }
  - { src: 'conf.d/system/portage/repos.conf', dest: '/etc/portage/repos.conf' }
  - { src: 'conf.d/system/portage/make.conf', dest: '/etc/portage/make.conf' }
  - { src: 'conf.d/system/portage/package.accept_keywords', dest: '/etc/portage/package.accept_keywords' }
  - { src: 'conf.d/system/portage/package.keywords', dest: '/etc/portage/package.keywords' }
  - { src: 'conf.d/system/portage/package.license', dest: '/etc/portage/package.license' }
  - { src: 'conf.d/system/portage/package.unmask', dest: '/etc/portage/package.unmask' }
  - { src: 'conf.d/system/udev.d/95-external-head-hotplug.rules', dest: '/etc/udev/rules.d/95-external-head-hotplug.rules' }
portage_overlays:
  - booboo
  - chaos
  - dilfridge
  - emacs
  - flow
  - go-overlay
  - haskell
  - jorgicio
  - lisp
  - mva
  - qwin-overlay
  - raiagent
  - posativ
  # - my_local_overlay # TODO manage local overlay somehow
packages_of_interest:
  - 'gnome-extra/nm-applet'
  - 'media-sound/volumeicon'
  - 'net-misc/dropbox'
  - 'sys-apps/dbus'
  - 'sys-fs/udisks-glue'
  # - 'x11-apps/copyq'
  - 'x11-apps/xmodmap'
  - 'x11-apps/xrdb'
  - 'x11-misc/autocutsel'
  - 'x11-misc/kbdd'
  - 'x11-misc/redshift'
  - 'x11-misc/trayer-srg'
  - 'x11-misc/unclutter'
  - 'x11-misc/xxkb'
  - 'x11-terms/rxvt-unicode'
  - 'x11-misc/yeganesh'
  - 'dev-util/rtags'
  - 'mail-filter/imapfilter'
  - 'app-emulation/docker'
  - 'app-emulation/docker-compose'
  - 'app-emulation/docker-machine'
  - 'app-emulation/docker-swarm'
  - 'dev-util/cargo'
  - 'sys-power/acpi'
  - 'sys-power/upower-pm-utils'
  - 'app-text/pandoc' #TODO: try to keep it here or try to build in Docker container
  - 'net-misc/urlview'
  - 'sys-libs/gpm'
  - 'sys-apps/fbset'
  - 'app-doc/zeal'
  - 'sys-apps/ripgrep'
  - 'app-shells/fzf'
  - 'net-misc/rclone-bin'
  - 'app-admin/apache-tools'
  - 'app-misc/jrnl'
  - 'app-admin/pass'
  - "net-irc/hexchat"
  - "app-misc/tmux"
  - "app-misc/tmux-mem-cpu-load"
  - "x11-apps/arbtt"
  - "dev-vcs/git-annex"
  - "app-text/pandoc"
  - "app-misc/jq"
  - "app-benchmarks/wrk"
  - "dev-python/isort"
  - "dev-util/strace"
  - "dev-util/ltrace"
  - "net-im/telegram-cli"
python_pip_packages:
  - "importmagic"
  - "snakeviz"
  - "jedi"
  - "flake8"
  - "autopep8"
  - "yapf"
  - "traad"
homedir_subdirs:
  - '.imapfilter'
  - '.arbtt'
  - '.tmux/plugins'
  - '.ssh'
  - '.config/twmn'
  - '.config/i3'
  - '.sawfish'
  - '.local/share/applications'
  - '.gnupg'
  - 'pids'
homedir_symlinks:
  - { src: 'conf.d/X11/.Xresources', dest: '.Xresources' }
  - { src: 'conf.d/X11/.i3status.conf', dest: '.i3status.conf' }
  - { src: 'conf.d/X11/.xxkbrc', dest: '.xxkbrc' }
  - { src: 'conf.d/X11/categorize.cfg', dest: '.arbtt/categorize.cfg' }
  - { src: 'conf.d/X11/twmn.conf', dest: '.config/twmn/twmn.conf' }
  - { src: 'conf.d/X11/xmodmaprc', dest: 'xmodmaprc' }
  - { src: 'conf.d/X11/i3.conf', dest: '.config/i3/config' }
  - { src: 'conf.d/X11/.sawfishrc', dest: '.sawfish/rc' }
  - { src: 'conf.d/user/.tmux.conf', dest: '.tmux.conf' }
  - { src: 'conf.d/user/.urlview', dest: '.urlview' }
  - { src: 'conf.d/user/browser/.conkerorrc', dest: '.conkerorrc' }
  - { src: 'conf.d/user/browser/.vimperatorrc', dest: '.vimperatorrc' }
  - { src: 'conf.d/user/common_settings', dest: 'common_settings' }
  - { src: 'conf.d/user/common_settings_bash', dest: 'common_settings_bash' }
  - { src: 'conf.d/user/tmux-sessions', dest: 'tmux-sessions' }
  - { src: 'conf.d/user/dev/.pylintrc', dest: '.pylintrc' }
  - { src: 'conf.d/user/dev/flake8', dest: '.config/flake8' }
  - { src: 'conf.d/user/dev/pep8', dest: '.config/pep8' }
  - { src: 'conf.d/user/gpg-agent.conf', dest: '.gnupg/gpg-agent.conf' }
  - { src: 'conf.d/user/mail/.mailcap', dest: '.mailcap' }
  - { src: 'conf.d/user/mail/.mbsyncrc', dest: '.mbsyncrc' }
  - { src: 'conf.d/user/mail/.msmtprc', dest: '.msmtprc' }
  - { src: 'conf.d/user/ssh_config', dest: '.ssh/config' }
  - { src: 'conf.d/user/zsh/.zsh', dest: '.zsh' }
  - { src: 'conf.d/user/zsh/.zshrc', dest: '.zshrc' }
  - { src: 'conf.d/user/.stalonetrayrc', dest: '.stalonetrayrc' }
  - { src: 'conf.d/user/.gmrunrc', dest: '.gmrunrc' }
  - { src: 'conf.d/user/emacsclient.desktop', dest: '.local/share/applications/emacsclient.desktop' }
mime_assocs:
  - { program: 'firefox', mimetype: 'text/html' }
  - { program: 'vlc', mimetype: 'video/avi' }
  - { program: 'vlc', mimetype: 'video/mpeg' }
  - { program: 'vlc', mimetype: 'video/x-flv' }
  - { program: 'vlc', mimetype: 'video/mp4' }
  - { program: 'vlc', mimetype: 'video/x-ms-wmv' }
  - { program: 'vlc', mimetype: 'video/x-matroska' }
  - { program: 'zathura', mimetype: 'application/pdf' }
  - { program: 'zathura', mimetype: 'application/x-pdf' }
  - { program: 'zathura', mimetype: 'image/vnd.djvu' }
  - { program: 'zathura', mimetype: 'image/x-djvu' }
  - { program: 'feh', mimetype: 'image/jpeg' }
  - { program: 'feh', mimetype: 'image/png' }
  - { program: 'abiword', mimetype: 'application/msword' }
common_settings_basenames:
  - common_settings
  - common_settings_bash
