- hosts: localhost

  tasks:

    - name: ensure some directories exist
      file:
        path={{ ansible_env.HOME }}/{{ item }}
        state=directory
      with_items:
        - '.imapfilter'
        - '.arbtt'
        - '.tmux/plugins'
        - '.ssh'
        - '.config/twmn'
        - '.config/i3'

    - name: make homedir symlinks
      file:
        src={{ playbook_dir }}/../{{ item.src }}
        dest={{ ansible_env.HOME }}/{{ item.dest }}
        state=link
      with_items:
        - { src: 'conf.d/X11/.Xresources', dest: '.Xresources' }
        - { src: 'conf.d/X11/.i3status.conf', dest: '.i3status.conf' }
        - { src: 'conf.d/X11/.xsession', dest: '.xsession' }
        - { src: 'conf.d/X11/.xxkbrc', dest: '.xxkbrc' }
        - { src: 'conf.d/X11/categorize.cfg', dest: '.arbtt/categorize.cfg' }
        - { src: 'conf.d/X11/twmn.conf', dest: '.config/twmn/twmn.conf' }
        - { src: 'conf.d/X11/xmodmaprc', dest: 'xmodmaprc' }
        - { src: 'conf.d/X11/i3.conf', dest: '.config/i3/config' }
        - { src: 'conf.d/user/.tmux.conf', dest: '.tmux.conf' }
        - { src: 'conf.d/user/browser/.conkerorrc', dest: '.conkerorrc' }
        - { src: 'conf.d/user/browser/.vimperatorrc', dest: '.vimperatorrc' }
        - { src: 'conf.d/user/common_settings', dest: 'common_settings' }
        - { src: 'conf.d/user/common_settings_bash', dest: 'common_settings_bash' }
        - { src: 'conf.d/user/dev/.pylintrc', dest: '.pylintrc' }
        - { src: 'conf.d/user/gpg-agent.conf', dest: '.gnupg/gpg-agent.conf' }
        - { src: 'conf.d/user/mail/.mailcap', dest: '.mailcap' }
        - { src: 'conf.d/user/mail/.mbsyncrc', dest: '.mbsyncrc' }
        - { src: 'conf.d/user/mail/.msmtprc', dest: '.msmtprc' }
        - { src: 'conf.d/user/ssh_config', dest: '.ssh/config' }
        - { src: 'conf.d/user/zsh/.zsh', dest: '.zsh' }
        - { src: 'conf.d/user/zsh/.zshrc', dest: '.zshrc' }
        - { src: 'conf.d/user/.stalonetrayrc', dest: '.stalonetrayrc' }
        - { src: 'templates/emacsclient.desktop', dest: '.local/share/applications/emacsclient.desktop' }

    - name: install tmux plugin manager
      git:
        repo=https://github.com/tmux-plugins/tpm
        dest={{ ansible_env.HOME }}/.tmux/plugins/tpm
      when: False

    - name: bash | source common settings
      lineinfile:
        dest={{ ansible_env.HOME }}/.bashrc
        line='source ~/common_settings_bash'
        state=present

- include: generate_imapfilter_config.yml
