- hosts: localhost

  tasks:

    - name: ensure some _system_ directories exist
      file:
        path={{ item }}
        state=directory
        mode=0755
        owner=octocat
        group=octocat
        recurse=yes
      sudo: yes
      with_items:
        - '/etc/custom_vpn'

    - name: ensure some packages installed (Gentoo)
      portage: package={{ item }} state=present
      with_items:
        - 'gnome-extra/nm-applet'
        - 'media-sound/volumeicon'
        - 'net-misc/dropbox'
        - 'sys-apps/dbus'
        - 'sys-fs/udisks-glue'
        # - 'x11-apps/copyq'
        - 'x11-apps/xmodmap'
        - 'x11-apps/xrdb'
        - 'x11-misc/autocutsel'
        - 'x11-misc/kbdd'
        - 'x11-misc/redshift'
        - 'x11-misc/trayer-srg'
        - 'x11-misc/unclutter'
        - 'x11-misc/xxkb'
        - 'x11-terms/rxvt-unicode'
        - 'x11-misc/yeganesh'
        - 'dev-util/rtags'
        - 'mail-filter/imapfilter'
        - 'app-emulation/docker'
        - 'app-emulation/docker-compose'
        - 'app-emulation/docker-machine'
        - 'app-emulation/docker-swarm'
        - 'dev-util/cargo'
        - 'sys-power/acpi'
      sudo: yes
      when: ansible_distribution == "Gentoo"

    - name: clean up system files in favor of symlinks
      file:
        path={{ item }}
        state=absent
      sudo: yes
      with_items:
        - '/etc/acpi'
        - '/etc/X11/xorg.conf.d'
        - '/etc/conf.d/docker'
        - '/etc/mpd.conf'
        - '/etc/portage/package.mask'
        - '/etc/portage/package.use'
        - '/etc/portage/repos.conf'
        - '/etc/portage/make.conf'
        - '/etc/portage/package.accept_keywords'
        - '/etc/portage/package.keywords'
        - '/etc/portage/package.license'
        - '/etc/portage/package.unmask'

    - name: make system symlinks
      file:
        src={{ playbook_dir }}/../{{ item.src }}
        dest={{ item.dest }}
        state=link
      sudo: yes
      with_items:
        - { src: 'conf.d/system/acpi', dest: '/etc/acpi' }
        - { src: 'conf.d/system/xorg.conf.d', dest: '/etc/X11/xorg.conf.d' }
        - { src: 'conf.d/system/docker', dest: '/etc/conf.d/docker' }
        - { src: 'conf.d/system/mpd.conf', dest: '/etc/mpd.conf' }
        - { src: 'conf.d/system/portage/package.mask', dest: '/etc/portage/package.mask' }
        - { src: 'conf.d/system/portage/package.use', dest: '/etc/portage/package.use' }
        - { src: 'conf.d/system/portage/repos.conf', dest: '/etc/portage/repos.conf' }
        - { src: 'conf.d/system/portage/make.conf', dest: '/etc/portage/make.conf' }
        - { src: 'conf.d/system/portage/package.accept_keywords', dest: '/etc/portage/package.accept_keywords' }
        - { src: 'conf.d/system/portage/package.keywords', dest: '/etc/portage/package.keywords' }
        - { src: 'conf.d/system/portage/package.license', dest: '/etc/portage/package.license' }
        - { src: 'conf.d/system/portage/package.unmask', dest: '/etc/portage/package.unmask' }

    - name: prepare global gitconfig
      template: src=../conf.d/user/dev/gitconfig.template dest=/etc/gitconfig
      sudo: yes

    - name: mount portage build directory as tmpfs
      sudo: yes
      lineinfile:
        dest=/etc/fstab
        line='tmpfs                   /var/tmp/portage/       tmpfs   uid=250,gid=250,size=10G,mode=0775      0 1'
        state=present
