- hosts: localhost

  vars:
    mail_configs_dir: "{{ playbook_dir }}/../conf.d/user/mail"
    imapfilter_d_path: "{{ mail_configs_dir }}/imapfilter.d"
    imapfilter_config: "{{ mail_configs_dir }}/imapfilter-config.lua"

  tasks:

    - name: remove old config file
      file: path="{{ imapfilter_config }}" state=absent

    - name: seed base config
      shell: "cat {{ mail_configs_dir }}/imapfilter-base.lua >> {{ imapfilter_config }} && echo -e -n '\n' >> {{ imapfilter_config }}"

    - name: populate with account configs
      shell: "cat {{ item }} >> {{ imapfilter_config }} && echo -e -n '\n' >> {{ imapfilter_config }}"
      with_fileglob:
        - "{{ imapfilter_d_path }}/*"

    - name: copy generated config file
      copy: src="{{ imapfilter_config }}" dest={{ ansible_env.HOME }}/.imapfilter/config.lua

    - name: Remove generated config file
      file: path="{{ imapfilter_config }}" state=absent
