- hosts: localhost

  tasks:

    - include_vars: common_vars.yml
      tags:
        - always

    - name: ensure some system dirs exists
      file:
        path={{ item }}
        state=directory
      become: true
      with_items: "{{ system_dirs }}"
      tags:
        - system
        - prepare

    - name: clean up system files in favor of symlinks
      file:
        path={{ item }}
        state=absent
      become: true
      with_items: "{{ entries_to_symlinks }}"
      tags:
        - system
        - prepare-cleanup

    - name: make system symlinks
      file:
        src={{ project_root }}/{{ item.src }}
        dest={{ item.dest }}
        state=link
      become: true
      with_items: "{{ system_symlinks }}"
      tags:
        - system

    - name: add overlays
      layman:
        name={{ item }}
        state=present
      with_items: "{{ portage_overlays }}"
      when: ansible_distribution == "Gentoo"
      tags:
        - system
        - portage

    # TODO think of moving this to shell level
    # consult with "world" file
    # reduce time for checks
    - name: ensure some packages installed (Gentoo)
      portage: package={{ item }} state=present
      with_items: "{{ packages_of_interest }}"
      become: true
      when: ansible_distribution == "Gentoo"
      tags:
        - system
        - portage

    - name: prepare global gitconfig
      template: src={{ project_root }}/conf.d/user/dev/gitconfig.template dest=/etc/gitconfig
      become: true
      tags:
        - system
        - dev

    - name: mount portage build directory as tmpfs
      become: true
      lineinfile:
        dest=/etc/fstab
        line='tmpfs                   /var/tmp/portage/       tmpfs   uid=250,gid=250,size=10G,mode=0775      0 1'
        state=present
      tags:
        - system
        - portage

    - name: symlink local overlay files
      file:
        src={{ project_root }}/conf.d/system/local_overlay
        dest=/usr/local/portage
        state=link
      become: true
      tags:
        - system
        - portage

    - name: ensure some directories exist
      file:
        path={{ ansible_env.HOME }}/{{ item }}
        state=directory
      with_items: "{{ homedir_subdirs }}"
      tags:
        - homedir
        - prepare

    - name: make homedir symlinks
      file:
        src={{ project_root }}/{{ item.src }}
        dest={{ ansible_env.HOME }}/{{ item.dest }}
        state=link
      with_items: "{{ homedir_symlinks }}"
      tags:
        - homedir

    - name: instantiate common settings
      template: src={{ project_root }}/conf.d/user/{{ item }}.template dest={{ ansible_env.HOME }}/{{ item }}
      with_items:
        - "{{ common_settings_basenames }}"
      tags:
        - homedir
        - common-settings

    - stat: path={{ ansible_env.HOME }}/.bashrc
      register: bashrc
      tags:
        - homedir
        - bash

    - name: bash | source common settings
      lineinfile:
        dest={{ ansible_env.HOME }}/.bashrc
        line='source ~/common_settings_bash'
        state=present
      when:
        bashrc.stat.exists == True
      tags:
        - homedir
        - bash

    - include_vars: common_vars.yml
      tags:
        - always

    - name: Buildapp | clone repo
      git:
        repo={{ buildapp_traits.clone_from }}
        dest={{ buildapp_traits.local_path }}
        force=yes
      tags:
        - buildapp
        - infra
        - remote

    - name: Buildapp | build
      make:
        chdir: "{{ buildapp_traits.local_path }}"
        target: buildapp
      tags:
        - buildapp
        - infra

    - name: Buildapp | install
      make:
        chdir: "{{ buildapp_traits.local_path }}"
        target: install
      become: yes
      tags:
        - buildapp
        - infra

    - name: tools | generate openrc templates
      template: src={{ project_root }}/conf.d/system/openrc/{{ item }}.openrc dest=./{{ item }}.openrc.entry
      with_items: "{{ openrc_services_list }}"
      tags:
        - openrc

    - name: tools | install openrc entries
      copy: src={{ item }}.openrc.entry dest=/etc/init.d/{{ item }} mode=0755
      become: true
      with_items: "{{ openrc_services_list }}"
      tags:
        - openrc

    - name: tools | openrc local cleanup
      file: path={{ item }}.openrc.entry state=absent
      with_items:  "{{ openrc_services_list }}"
      tags:
        - openrc

    - name: accompanying tools | shepherd build (mail checking tool)
      make:
        chdir: "{{ project_root }}/src/shepherd"
        target: all
      tags:
        - shepherd
        - mail

    - name: accompanying tools | shepherd install (mail checking tool)
      shell: "mv {{ project_root }}/src/shepherd/builds/shepherd {{ project_root }}/utils/shepherd"
      tags:
        - shepherd
        - mail

    - name: accompanying tools | shepherd | restart service
      service: name=shepherd state=restarted
      become: true
      tags:
        - shepherd
        - service

    - name: ensure VPN custom config directory exist
      file:
        path={{ item }}
        state=directory
        mode=0755
        owner=octocat
        group=octocat
        recurse=yes
      become: true
      with_items:
        - '/etc/custom_vpn'
      tags:
        - vpn
        - prepare

    - name: cleanup VPN custom config directory
      file:
        path: "{{ item }}"
        state: absent
      with_fileglob:
        - "/etc/custom_vpn/*"
      tags:
        - vpn
        - prepare-cleanup

    - name: vpn | copy files to system location
      copy:
        src="{{ project_root }}/private/{{ item.src }}"
        dest={{ item.dest }}
      become: true
      with_items:
        - { src: 'current/auth.conf', dest: '/etc/custom_vpn/auth.conf' }
        - { src: 'current/office.ovpn', dest: '/etc/custom_vpn/office.ovpn' }
      tags:
        - vpn

    - name: vpn | customize OpenVPN config | automate authentication # TODO: check if "script-security 2" matters
      lineinfile:
        dest=/etc/custom_vpn/office.ovpn
        regexp="^auth-user-pass"
        line="auth-user-pass /etc/custom_vpn/auth.conf"
      become: yes
      tags:
        - vpn

    - name: vpn | customize OpenVPN config | fix up/down scripting
      lineinfile:
        dest=/etc/custom_vpn/office.ovpn
        regexp={{ item.regexp }}
        line={{ item.line }}
      with_items:
        - { regexp: "^up /etc/openvpn/update-resolv-conf", line: "up /etc/openvpn/up.sh" }
        - { regexp: "^down /etc/openvpn/update-resolv-conf", line: "down /etc/openvpn/down.sh" }
      become: yes
      when: ansible_distribution == "Gentoo"
      tags:
        - vpn

    - name: vpn | restart service
      service: name=job-vpn state=restarted
      become: true
      tags:
        - vpn
        - service

    - name: git-quick-stats | clone repository
      git:
        repo={{ gqs_traits.clone_from }}
        dest={{ gqs_traits.local_path }}
        force=yes
      tags:
        - cli
        - gqs
        - remote

    - name: git-quick-stats | install
      make:
        chdir: "{{ gqs_traits.local_path }}"
        target: install
      become: yes
      tags:
        - cli
        - gqs

    - name: git-quick-stats | uninstall
      make:
        chdir: "{{ gqs_traits.local_path }}"
        target: uninstall
      tags:
        - uninstall

    - name: download Telegram Desktop archive
      get_url:
        url: https://updates.tdesktop.com/tlinux/tsetup.{{ telegram_version }}.tar.xz
        dest: /tmp/tsetup.tar.xz
        force: yes
      tags:
        - tg
        - remote

    - name: update Telegram Desktop binaries
      unarchive:
        src: /tmp/tsetup.tar.xz
        dest: /usr/local/bin
        extra_opts:
          - "--strip=1"
      become: true
      tags:
        - tg

    - name: sshuttle | restart service
      service: name=sshuttle state=restarted
      become: true
      tags:
        - sshuttle
        - service

    - name: install tmux plugin manager
      git:
        repo=https://github.com/tmux-plugins/tpm
        dest={{ ansible_env.HOME }}/.tmux/plugins/tpm
      tags:
        - tmux
        - remote

    - name: tmuxifier | clone repo
      git:
        repo={{ tmuxifier_traits.clone_from }}
        dest={{ tmuxifier_traits.local_path }}
        force=yes
      tags:
        - tmux
        - remote

    - name: tmuxifier | update configs
      lineinfile:
        dest: "{{ project_root }}/conf.d/user/{{ item[0] }}"
        line: "{{ item[1].line }}"
        insertafter: "{{ item[1].after }}"
        state: present
      with_nested:
        - "{{ common_settings_basenames }}"
        - [{ line: "\t$HOME/.tmuxifier/bin", after: "^BIN_DIRS=\\(" },
           { line: "\neval \"$(tmuxifier init -)\"", after: "EOF"}]
      tags:
        - tmux
    # TODO: think of way to rerun some links/path population steps after this

    - name: imapfilter | remove old config file
      file: path="{{ imapfilter_config }}" state=absent
      tags:
        - mail

    - name: imapfilter | seed base config
      shell: "cat {{ mail_configs_dir }}/imapfilter-base.lua >> {{ imapfilter_config }} && echo -e -n '\n' >> {{ imapfilter_config }}"
      tags:
        - mail

    - name: imapfilter | populate with account configs
      shell: "cat {{ item }} >> {{ imapfilter_config }} && echo -e -n '\n' >> {{ imapfilter_config }}"
      with_fileglob:
        - "{{ imapfilter_d_path }}/*"
      tags:
        - mail

    - name: imapfilter | copy generated config file
      copy: src="{{ imapfilter_config }}" dest={{ ansible_env.HOME }}/.imapfilter/config.lua
      tags:
        - mail

    - name: imapfilter | Remove generated config file
      file: path="{{ imapfilter_config }}" state=absent
      tags:
        - mail

    - name: register org-protocol handler in mimeapps
      lineinfile:
        dest={{ ansible_env.HOME }}/.local/share/applications/mimeapps.list
        line=x-scheme-handler/org-protocol=emacsclient.desktop
        state=present
      tags:
        - assoc

    - name: setup xdg-open associations
      shell: xdg-mime default {{ item.program }}.desktop {{ item.mimetype }}
      with_items: "{{ mime_assocs }}"
      tags:
        - assoc

    - include_vars: xsession_vars.yml
      tags:
        - xsession

    - name: generate .xsession script
      template: src={{ project_root }}/conf.d/X11/.xsession.template dest={{ ansible_env.HOME }}/.xsession
      tags:
        - xsession

    - name: ensure .xsession permissions
      file:
        path: "{{ ansible_env.HOME }}/.xsession"
        mode: 0755
      tags:
        - xsession

    - name: addrlookup | clone repo
      git:
        repo={{ addrlookup_traits.clone_from }}
        dest={{ addrlookup_traits.local_path }}
        force=yes
      tags:
        - notmuch
        - remote

    - name: addrlookup | build
      shell: make
      args:
        chdir: '{{ addrlookup_traits.local_path }}'
      tags:
        - notmuch

    - name: addrlookup | install binary
      shell: "mv {{ addrlookup_traits.local_path }}/notmuch-addrlookup /usr/bin"
      become: true
      tags:
        - notmuch

    - name: addrlookup | ensure binary permissions
      file:
        path: "/usr/bin/notmuch-addrlookup"
        mode: 0644
        owner: root
        group: root
      become: true
      tags:
        - notmuch

    - name: httplab | install
      shell: go get github.com/gchaincl/httplab
      tags:
        - devtools

      # TODO: https://github.com/asciimoo/wuzz - master/HEAD is broken (SIGSEGV), try later

    - name: Zshnip | clone repo
      git:
        repo={{ zshnip_traits.clone_from }}
        dest={{ zshnip_traits.local_path }}
        force=yes
      tags:
        - cli
        - zshnip

    - name: Zshnip | copy file(s)
      copy:
        src="{{ zshnip_traits.local_path }}/zshnip.zsh"
        dest="{{ project_root }}/utils"
      tags:
        - cli
        - zshnip

    - name: Zshnip | configure Zsh
      lineinfile:
        dest="{{ project_root }}/conf.d/user/zsh/.zsh/custom"
        line="source zshnip.zsh"
        state=present
      tags:
        - cli
        - zshnip

    - name: Zshnip | configure Zsh | bind keys
      lineinfile:
        path: "{{ project_root }}/conf.d/user/zsh/.zsh/bindkeys"
        line: "{{ item }}"
      with_items:
        - "\nbindkey '\ej' zshnip-expand-or-edit"
        - "bindkey '\ee' zshnip-edit-and-expand"
      tags:
        - cli
        - zshnip

    - name: start devdns
      docker_container:
        name: devdns
        image: ruudud/devdns
        state: started
        expose:
          - 53:53/udp
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
      tags:
        - devtools
        - docker
        - infra

    - name: setup devdns host <-> containers resolving
      blockinfile:
        path: /etc/dhcp/dhclient.conf
        block: |
          supersede domain-name "dev";
          prepend domain-name-servers 127.0.0.1;
      become: true
      tags:
        - devtools
        - docker
        - infra

    - name: install pip packages (Python)
      pip:
        name: "{{ item }}"
        state: latest
        extra_args: --user
      with_items: "{{ python_pip_packages }}"
      tags:
        - devtools
        - python-libs

    - name: stop devdns container
      docker_container:
        name: devdns
        state: stopped
      tags:
        - prepare-cleanup

    - name: remove devdns host <-> containers resolving
      blockinfile:
        path: /etc/dhcp/dhclient.conf
        block: |
          supersede domain-name "dev";
          prepend domain-name-servers 127.0.0.1;
        state: absent
      become: true
      tags:
        - prepare-cleanup

    - name: Hexchat | download theme
      get_url:
        url: https://dl.hexchat.net/themes/Zenburn.hct
        dest: /tmp/Zenburn.hct
        force: yes
      tags:
        - IRC
        - remote

    - name: Hexchat | apply theme
      unarchive:
        src: /tmp/Zenburn.hct
        dest: "{{ ansible_env.HOME }}/.config/hexchat"
      tags:
        - IRC

    - name: THD | clone repo
      git:
        repo={{ thd_traits.clone_from }}
        dest={{ thd_traits.local_path }}
        force=yes
      tags:
        - cli
        - thd

    - name: THD | update config
      template: src={{ project_root }}/conf.d/user/thd_config.template dest={{ thd_traits.local_path }}/config.yaml
      tags:
        - cli
        - thd

    - name: THD | start telegram-cli
      shell: "nohup telegram-cli --json -P {{ tg_cli_port }} -v 0 &"
      tags:
        - cli
        - thd

    - name: THD | perform dump
      shell: "ruby telegram-history-dump.rb{% if tg_backup_kill_tg %} --kill-tg{% endif %}"
      args:
        chdir: '{{ thd_traits.local_path }}'
      tags:
        - cli
        - thd
