- hosts: localhost
  roles:
    - role: portage
      actions:
        - bootstrap
        - setup
    - role: services
      remote_domain: <example.com> # substitute for real value
      restart: yes
      actions: [] # TODO: provide "dry-run" for testing
    - role: x11
      actions:
        - bootstrap
        - setup
        - xsession
    - role: workplace
      actions:
        - bootstrap
        - setup
    - role: dev
      docker_options: --insecure-registry example.com:5000 # substitute for real value
      actions:
        - bootstrap
        - setup
    - role: tools
      telegram_version: 1.1.7
      actions:
        - bootstrap
        - setup
