- hosts: localhost

  tasks:

    - name: get work dir
      shell: pwd
      register: workdir

    - name: vpn | copy files to system location
      copy:
        src={{ workdir.stdout }}/../vpn/{{ item.src }}
        dest={{ item.dest }}
      sudo: yes
      with_items:
        - { src: 'auth.conf', dest: '/etc/custom_vpn/auth.conf' }
        - { src: 'office-tcp.ovpn', dest: '/etc/custom_vpn/office-tcp.ovpn' }
        - { src: 'office-udp.ovpn', dest: '/etc/custom_vpn/office-udp.ovpn' }

    - name: vpn | generate openrc entry
      template: src=templates/job-vpn.openrc dest=./job-vpn.openrc.entry

    - name: vpn | install openrc entry
      copy: src=job-vpn.openrc.entry dest=/etc/init.d/job-vpn mode=0755
      sudo: yes

    - name: vpn | restart service
      service: name=job-vpn state=restarted
      sudo: yes

    - name: vpn | openrc cleanup
      file: path=job-vpn.openrc.entry state=absent
