- hosts: localhost

  vars:
    ripgrep_repo_location: /tmp/ripgrep

  tasks:

    - name: get work dir
      shell: pwd
      register: workdir

    - name: accompanying tools | bootstrap Buildapp tool
      shell: sbcl --eval "(ql:quickload 'buildapp)" --eval "(buildapp:build-buildapp \"{{ workdir.stdout }}/../utils/buildapp\")"

    - name: accompanying tools | shepherd build (mail checking tool)
      # TODO: migrate to buildapp
      shell: sbcl --eval "(pushnew (truename \"{{ workdir.stdout }}/../src/\") ql:*local-project-directories*)" --eval "(ql:register-local-projects)" --eval "(ql:quickload 'shepherd)" --eval "(shepherd::save-image-shepherd)"

    - name: accompanying tools | shepherd install (mail checking tool)
      shell: "mv {{ workdir.stdout }}/shepherd {{ workdir.stdout }}/../utils/shepherd"

    - name: vpn | copy files to system location
      copy:
        src={{ workdir.stdout }}/../private/{{ item.src }}
        dest={{ item.dest }}
      sudo: yes
      with_items:
        - { src: 'auth.conf', dest: '/etc/custom_vpn/auth.conf' }
        - { src: 'office-tcp.ovpn', dest: '/etc/custom_vpn/office-tcp.ovpn' }
        - { src: 'office-udp.ovpn', dest: '/etc/custom_vpn/office-udp.ovpn' }

    - name: ripgrep | clone repository
      git:
        repo=https://github.com/BurntSushi/ripgrep
        dest={{ ripgrep_repo_location }}
        force=yes

    - name: ripgrep | build
      shell: cargo build --release
      args:
          chdir: '{{ ripgrep_repo_location }}'

    - name: ripgrep | install binary
      shell: "mv {{ ripgrep_repo_location }}/target/release/rg {{ workdir.stdout }}/../utils/rg"

    - name: make system symlinks
      file:
        src={{ workdir.stdout }}/../utils/rg
        dest=/usr/bin/rg
        state=link
      sudo: yes
