- hosts: localhost
  roles:
    - role: portage
      actions:
        - bootstrap
        - setup
    - role: services
      remote_domain: <example.com> # substitute for real value
      restart: yes
      actions: [] # TODO: provide "dry-run" for testing
    - role: x11
      actions:
        - bootstrap
        - setup
        - xsession
    - role: workplace
      actions:
        - bootstrap
        - setup
