- hosts: localhost

  vars:
    ripgrep_repo_location: /tmp/ripgrep

  tasks:

    - include_vars: common_vars.yml
      tags:
        - cl_tools
        - vpn
        - cli

    - name: accompanying tools | bootstrap Buildapp tool
      shell: sbcl --eval "(ql:quickload 'buildapp)" --eval "(buildapp:build-buildapp \"{{ project_root }}/utils/buildapp\")"
      tags:
        - cl_tools

    - name: accompanying tools | shepherd build (mail checking tool)
      # TODO: migrate to buildapp
      shell: sbcl --eval "(pushnew (truename \"{{ project_root }}/src/\") ql:*local-project-directories*)" --eval "(ql:register-local-projects)" --eval "(ql:quickload 'shepherd)" --eval "(shepherd::save-image-shepherd)"
      tags:
        - cl_tools

    - name: accompanying tools | shepherd install (mail checking tool)
      shell: "mv {{ playbook_dir }}/shepherd {{ project_root }}/utils/shepherd"
      tags:
        - cl_tools

    - name: ensure VPN custom config directory exist
      file:
        path={{ item }}
        state=directory
        mode=0755
        owner=octocat
        group=octocat
        recurse=yes
      become: true
      with_items:
        - '/etc/custom_vpn'
      tags:
        - vpn

    - name: cleanup VPN custom config directory
      file:
        path: "{{ item }}"
        state: absent
      with_fileglob:
        - "/etc/custom_vpn/*"
      tags:
        - vpn

    - name: vpn | copy files to system location
      copy:
        src="{{ project_root }}/private/{{ item.src }}"
        dest={{ item.dest }}
      become: true
      with_items:
        - { src: 'current/auth.conf', dest: '/etc/custom_vpn/auth.conf' }
        - { src: 'current/office.ovpn', dest: '/etc/custom_vpn/office.ovpn' }
      tags:
        - vpn

    - name: vpn | generate openrc entry
      template: src=../templates/job-vpn.openrc dest=./job-vpn.openrc.entry
      tags:
        - openrc

    - name: vpn | install openrc entry
      copy: src=job-vpn.openrc.entry dest=/etc/init.d/job-vpn mode=0755
      become: true
      tags:
        - openrc

    - name: vpn | restart service
      service: name=job-vpn state=restarted
      become: true
      tags:
        - openrc

    - name: vpn | openrc cleanup
      file: path=job-vpn.openrc.entry state=absent
      tags:
        - openrc

    - name: ripgrep | clone repository
      git:
        repo=https://github.com/BurntSushi/ripgrep
        dest={{ ripgrep_repo_location }}
        force=yes
      tags:
        - cli

    - name: ripgrep | build
      shell: cargo build --release
      args:
        chdir: '{{ ripgrep_repo_location }}'
      tags:
        - cli

    - name: ripgrep | install binary
      shell: "mv {{ ripgrep_repo_location }}/target/release/rg {{ project_root }}/utils/rg"
      tags:
        - cli

    - name: ripgrep | make system symlinks
      file:
        src={{ project_root }}/utils/rg
        dest=/usr/bin/rg
        state=link
      become: true
      tags:
        - cli

    - name: download Telegram Desktop archive
      get_url:
        url: https://updates.tdesktop.com/tlinux/tsetup.{{ telegram_version }}.tar.xz
        dest: /tmp/tsetup.tar.xz
      tags:
        - tg

    - name: update Telegram Desktop binaries
      unarchive:
        src: /tmp/tsetup.tar.xz
        dest: /usr/local/bin
        extra_opts:
          - "--strip=1"
      become: true
      tags:
        - tg
