---

- name: register current time
  shell: "date +%Y%m%d%H%M%S"
  register: current_run_timestamp
  tags:
    - always

# TODO think of moving this to shell level
# consult with "world" file
# reduce time for checks
- name: ensure some packages installed
  portage:
    package: "{{ item }}"
    state: present
  with_items: "{{ packages_of_interest }}"
  become: yes
  when:
    - "'setup' in actions"
    - check_packages_installed

- name: instantiate Docker config
  copy:
    content: "{{ lookup('template', 'docker.template') }}"
    dest: "/etc/conf.d/docker"
    mode: 0500
    owner: root
    group: root
  become: yes
  register: docker_config
  when:
    - "'setup' in actions"

- name: restart Docker service
  shell: rc-service docker restart
  become: yes
  when:
    - "'setup' in actions"
    - docker_config.changed

- name: copy homedir files
  copy:
    src: "{{ role_path }}/files/{{ item.src }}"
    dest: "{{ ansible_env.HOME }}/{{ item.dest }}"
    mode: 0755
  with_items: "{{ homedir_files }}"
  when:
    - "'setup' in actions"

- name: prepare global gitconfig
  copy:
    content: "{{ lookup('template', 'gitconfig.template') }}"
    dest: "/etc/gitconfig"
    mode: 0544
    owner: root
    group: root
  become: yes
  when:
    - "'setup' in actions"

- name: Buildapp | clone repo
  git:
    repo: "{{ buildapp_traits.clone_from }}"
    dest: "{{ buildapp_traits.local_path }}"
    force: yes
  when:
    - "'setup' in actions"

- name: Buildapp
  make:
    chdir: "{{ buildapp_traits.local_path }}"
    target: "{{ item }}"
  with_items:
    - buildapp
    - install
  become: yes
  when:
    - "'setup' in actions"

- name: install pip packages (Python)
  pip:
    name: "{{ item }}"
    state: latest
    extra_args: --user
  with_items: "{{ python_pip_packages }}"
  when:
    - "'setup' in actions"
