---

- name: register current time
  shell: 'date +%Y%m%d%H%M%S'
  register: current_run_timestamp
  tags:
    - always

- name: ensure some system dirs exists
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  become: true
  with_items: "{{ system_dirs }}"
  when:
    - "'bootstrap' in actions"

- name: copy files
  copy:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "/etc/portage/{{ item }}"
    mode: 0755
  become: true
  with_items: "{{ portage_files }}"
  when:
    - "'setup' in actions"

- name: add overlays
  layman:
    name={{ item }}
    state=present
  become: yes
  with_items: "{{ portage_overlays }}"
  when:
    - False # temporarily disabled because of errors
    # - ansible_distribution == "Gentoo"
    # - "'setup' in actions"

# TODO think of moving this to shell level
# consult with "world" file
# reduce time for checks
- name: ensure some packages installed (Gentoo)
  portage: package={{ item }} state=present
  with_items: "{{ packages_of_interest }}"
  become: true
  when:
    - "'setup' in actions"
    - check_packages_installed

- name: symlink local overlay files # TODO: think of copy instead of linking
  file:
    src={{ role_path }}/files/local_overlay
    dest=/usr/local/portage
    state=link
  become: true
  when:
    - "'setup' in actions"

- name: mount portage build directory as tmpfs
  become: true
  lineinfile:
    dest=/etc/fstab
    line='tmpfs                   /var/tmp/portage/       tmpfs   uid=250,gid=250,size=10G,mode=0775      0 1'
    state=present
  when:
    - "'setup' in actions"
