#!/usr/bin/env zsh

BIN_DIRS=(
    $HOME/bin
    $HOME/tools/bin
    $HOME/workspace/configs/rc/utils
    /usr/lib/go/bin
    $HOME/workspace/gocode/bin
)

GOPATH=/home/octocat/workspace/gocode

# Remove dupes from 'path', which is array tied to 'PATH'
typeset -U path
for ((i=1; i<= $#BIN_DIRS; i++)) do
    for dir in $BIN_DIRS[i]; do
        if [ -d $dir ] ; then
            path=($dir "$path[@]")
        fi
    done
done

for candidate in emacsclient vim vi; do
    if [[ ! -z $(which $candidate) ]]; then
        export VISUAL=$candidate
        export EDITOR=$candidate
        break
    fi
done
