#!/usr/bin/env bash

tmux has-session -t 'var' 2>/dev/null
if [ "$?" -eq 1 ] ; then
    tmux new-session -s 'var' -d 'mc'
fi
tmux has-session -t 'work' 2>/dev/null
if [ "$?" -eq 1 ] ; then
    tmux new-session -s 'work' -d 'mc'
fi

tmux attach -t var
