---

system_dirs:
  - "/etc/portage"
  - "/etc/portage/package.mask"
  - "/etc/portage/package.use"
  - "/etc/portage/repos.conf"
  - "/etc/portage/env"
portage_files:
  - { name: "make.conf" }
  - { name: "package.accept_keywords" }
  - { name: "package.keywords" }
  - { name: "package.license" }
  - { name: "package.mask/kernels" }
  - { name: "package.mask/main" }
  - { name: "package.unmask" }
  - { name: "package.use/main" }
  - { name: "package.use/versioned" }
  - { name: "package.use/python_versions" }
  - { name: "package.use/ruby_versions" }
  - { name: "repos.conf/gentoo.conf", lookup: "template" }
  - { name: "package.env" }
  - { name: "env/debugsyms" }
  - { name: "env/installsources" }
overlays_data_location: /var/lib/layman
local_overlay_data_location: /usr/local/portage
aux_files:
  - "rc.conf"
portage_overlays:
  - dilfridge
  - emacs
  - go-overlay
  - haskell
  - lisp
  - mva
  - raiagent
  - octopus
overlays_check_official: no
packages_of_interest:
  - "app-admin/haskell-updater"
  - "app-portage/fetchcommandwrapper"
  - "app-portage/mirrorselect"
  - "app-portage/repoman"
check_packages_installed: no
tmpfs_dirs:
  - { path: "/var/tmp/portage/", uid: "250", gid: "250", size: "10G", mode: "0755"}
  - { path: "{{ ansible_env.HOME }}/.cache", uid: "1000", gid: "1000", size: "2G", mode: "0755"} # TODO: maybe connect with users data (ids, binaries, paths, etc.)
