---

- include_vars: xsession.yml

- name: register current time
  shell: "date +%Y%m%d%H%M%S"
  register: current_run_timestamp
  tags:
    - always

- name: shells | collect binaries
  shell: "which {{ item }}"
  register: user_shell_binaries
  with_items:
    - "{{ user_shells }}"
  tags:
    - always

- name: Populate shell binaries
  set_fact:
    user_shell_binaries: "{{ user_shell_binaries | default({}) | combine( {item.item: item.stdout} ) }}"
  with_items: "{{ user_shell_binaries.results }}"
  tags:
    - always

- name: ensure some system dirs exists
  file:
    path: "{{ item }}"
    state: directory
  become: yes
  with_items: "{{ system_dirs }}"
  when:
    - "'bootstrap' in actions"

- name: ensure home subdirs exist
  file:
    path: "{{ ansible_env.HOME }}/{{ item }}"
    state: directory
  with_items: "{{ homedir_subdirs }}"
  when:
    - "'bootstrap' in actions"

- name: copy system files
  copy:
    src: "{{ role_path }}/files/{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0755
  become: yes
  with_items: "{{ system_files }}"
  when:
    - "'setup' in actions"

- name: ensure default user traits
  user:
    name: "{{ default_user_name }}"
    shell: "{{ user_shell_binaries[default_user_shell] }}"
    groups: "{{ default_user_groups | join(',') }}"
  become: yes
  when:
    - "'setup' in actions"

# TODO think of moving this to shell level
# consult with "world" file
# reduce time for checks
- name: ensure some packages installed
  portage:
    package: "{{ item }}"
    state: present
  with_items: "{{ packages_of_interest }}"
  become: yes
  when:
    - "'setup' in actions"
    - check_packages_installed

- name: install pip packages (Python)
  pip:
    name: "{{ item }}"
    state: latest
    extra_args: --user
  with_items: "{{ python_pip_packages }}"
  when:
    - "'setup' in actions"

- name: copy homedir files
  copy:
    src: "{{ role_path }}/files/{{ item.src }}"
    dest: "{{ ansible_env.HOME }}/{{ item.dest }}"
    mode: 0755
  with_items: "{{ homedir_files }}"
  when:
    - "'setup' in actions"

- name: copy custom scripts
  copy:
    src: "{{ role_path }}/files/scripts/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    mode: 0755
  with_items: "{{ custom_scripts }}"
  become: yes
  when:
    - "'setup' in actions"

- name: instantiate common settings
  copy:
    content: "{{ lookup('template', '{{ item }}.template') }}"
    dest: "{{ ansible_env.HOME }}/{{ item }}"
    mode: 0755
  with_items:
    - "{{ common_settings_basenames }}"
  when:
    - "'setup' in actions"

- stat: path={{ ansible_env.HOME }}/.bashrc
  register: bashrc
  when:
    - "'setup' in actions"

- name: bash | source common settings
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.bashrc"
    line: "source ~/common_settings_bash"
    state: present
  when:
    - bashrc.stat.exists == True
    - "'setup' in actions"

- name: accompanying tools | shepherd build (mail checking tool)
  git:
    repo: "{{ shepherd_traits.clone_from }}"
    dest: "{{ shepherd_traits.local_path }}"
    force: yes
  tags:
    - shepherd

- name: accompanying tools | shepherd build (mail checking tool)
  make:
    chdir: "{{ shepherd_traits.local_path }}"
    target: all
  tags:
    - shepherd

- name: accompanying tools | shepherd install (mail checking tool)
  shell: "mv {{ shepherd_traits.local_path }}/builds/shepherd /usr/local/bin/shepherd"
  become: yes
  tags:
    - shepherd

- name: install tmux plugin manager
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: "{{ ansible_env.HOME }}/.tmux/plugins/tpm"
  when:
    - "'setup' in actions"

- name: imapfilter | remove old config file
  file:
    path: "{{ imapfilter_config }}"
    state: absent
  when:
    - "'setup' in actions"
  tags:
    - imapfilter

- name: imapfilter | seed base config
  shell: "cat {{ mail_configs_dir }}/imapfilter-base.lua >> {{ imapfilter_config }} && echo -e -n '\n' >> {{ imapfilter_config }}"
  when:
    - "'setup' in actions"
  tags:
    - imapfilter

- name: imapfilter | populate with account configs
  shell: "cat {{ item }} >> {{ imapfilter_config }} && echo -e -n '\n' >> {{ imapfilter_config }}"
  with_fileglob:
    - "{{ imapfilter_d_path }}/*"
  when:
    - "'setup' in actions"
  tags:
    - imapfilter

- name: imapfilter | copy generated config file
  copy:
    src: "{{ imapfilter_config }}"
    dest: "{{ ansible_env.HOME }}/.imapfilter/config.lua"
  when:
    - "'setup' in actions"
  tags:
    - imapfilter

- name: imapfilter | Remove generated config file
  file:
    path: "{{ imapfilter_config }}"
    state: absent
  when:
    - "'setup' in actions"
  tags:
    - imapfilter

- name: register org-protocol handler in mimeapps
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.local/share/applications/mimeapps.list"
    line: x-scheme-handler/org-protocol=emacsclient.desktop
    state: present
  when:
    - "'setup' in actions"

- name: setup xdg-open associations
  shell: "xdg-mime default {{ item.program }}.desktop {{ item.mimetype }}"
  with_items: "{{ mime_assocs }}"
  when:
    - "'setup' in actions"

- name: generate OSD statusbar script
  copy:
    content: "{{ lookup('template', 'statusbar_osd.template') }}"
    dest: "{{ binaries_prefix }}/statusbar_osd"
    mode: 0755
    owner: "{{ user_name }}"
    group: "{{ user_group }}"
  when:
    - "'setup' in actions"

- name: generate .xsession script
  copy:
    content: "{{ lookup('template', '.xsession.template') }}"
    dest: "{{ ansible_env.HOME }}/.xsession"
    mode: 0755
  register: xsession_script
  when:
    - "'xsession' in actions"

- name: instantiate templated configs
  copy:
    content: "{{ lookup('template', '{{ item.src }}') }}"
    dest: "{{ ansible_env.HOME }}/{{ item.dest }}"
    mode: 0755
  with_items: "{{ templated_configs }}"
  when:
    - "'setup' in actions"

- name: remove tangled Emacs config
  file:
    path: "{{ emacs_config_name_tangled }}"
    state: absent
  when:
    - xsession_script.changed

- name: backup bookmarks
  copy:
    src: "{{ item }}"
    dest: "{{ role_path }}/files/{{ item | basename }}"
    mode: 0755
  with_items:
    - "{{ emacs_bookmarks_file }}"
    - "{{ shell_bookmarks_file }}"
  when:
    - "'backup' in actions"

- name: restore bookmarks
  copy:
    src: "{{ role_path }}/files/{{ item | basename }}"
    dest: "{{ item }}"
    mode: 0755
  with_items:
    - "{{ emacs_bookmarks_file }}"
    - "{{ shell_bookmarks_file }}"
  when:
    - "'restore' in actions"

- name: instantiate Docker config
  copy:
    content: "{{ lookup('template', 'docker.template') }}"
    dest: "/etc/conf.d/docker"
    mode: 0500
    owner: root
    group: root
  become: yes
  register: docker_config
  when:
    - "'setup' in actions"

- name: restart Docker service
  shell: rc-service docker restart
  become: yes
  when:
    - "'setup' in actions"
    - docker_config.changed

- name: prepare global gitconfig
  copy:
    content: "{{ lookup('template', 'gitconfig.template') }}"
    dest: "/etc/gitconfig"
    mode: 0544
    owner: root
    group: root
  become: yes
  when:
    - "'setup' in actions"

- name: Buildapp | clone repo
  git:
    repo: "{{ buildapp_traits.clone_from }}"
    dest: "{{ buildapp_traits.local_path }}"
    force: yes
  when:
    - "'setup' in actions"

- name: Buildapp
  make:
    chdir: "{{ buildapp_traits.local_path }}"
    target: "{{ item }}"
  with_items:
    - buildapp
    - install
  become: yes
  when:
    - "'setup' in actions"

# TODO: put rc-update data under version control, e.g.:
# shell: rc-update add {{ item.name }} {{ item.level }}
# with_items: {{ rc_update_items }}
# and maybe export and delete all previous data before this
