- include_vars: "{{ item }}"
  tags: [appearance]
  with_items:
    - common.yml
    - appearance.yml

- name: instantiate resources configs
  tags: [appearance, configs]
  copy:
    content: "{{ lookup('template', '{{ item.src }}') }}"
    dest: "{{ ansible_env.HOME }}/{{ item.dest }}"
    mode: 0755
  with_items: "{{ resources_configs }}"

# TODO: generalize fonts installation

- name: Go fonts | clone repo
  tags: [appearance, fonts]
  git:
    repo: "{{ go_fonts_traits.clone_from }}"
    dest: "{{ go_fonts_traits.local_path }}"
    force: yes

- name: Go fonts | install
  tags: [appearance, fonts]
  copy:
    src: "{{ go_fonts_traits.local_path }}/{{ go_fonts_ttf_subpath }}"
    dest: "{{ fonts_ttf_location }}"
  become: yes

- name: Hexchat | download theme
  tags: [appearance, hexchat]
  get_url:
    url: https://dl.hexchat.net/themes/Zenburn.hct
    dest: /tmp/Zenburn.hct
    force: yes

- name: Hexchat | apply theme
  tags: [appearance, hexchat]
  unarchive:
    src: /tmp/Zenburn.hct
    dest: "{{ ansible_env.HOME }}/.config/hexchat"

# TODO: think of fonts setup automating (e.g. dowloading, copying, updating fontcache, whatever)
