---

- name: shells | collect binaries
  tags: [common]
  shell: "which {{ item }}"
  register: user_shell_binaries
  with_items:
    - "{{ user_shells }}"

- name: Populate shell binaries
  tags: [common]
  set_fact:
    user_shell_binaries: "{{ user_shell_binaries | default({}) | combine( {item.item: item.stdout} ) }}"
  with_items: "{{ user_shell_binaries.results }}"

- name: groups | current user primary group
  tags: [common]
  shell: "groups | cut -d' ' -f1"
  register: current_user_primary_group

- name: facts | current user primary group
  tags: [common]
  set_fact:
    current_user_primary_group: "{{ current_user_primary_group.stdout }}"
