---

- include_vars: "{{ item }}"
  tags: [containers]
  with_items:
    - containers.yml

- name: register current time
  shell: "date +%Y%m%d%H%M%S"
  register: current_run_timestamp
  tags: [always]

# DISCLAIMER: at the moment most of started containers are planned to stop/remove manually

- name: THD | prepare temporary dir
  tags: [containers, thd]
  copy:
    src: "{{ item.src }}/"
    dest: "{{ item.dest }}"
    mode: 0755
  with_items:
    - { src: "{{ role_path }}/files/thd", dest: "{{ thd_tmp_dir }}" }
    - { src: "{{ playbook_dir }}/../private/telegram", dest: "{{ thd_tmp_dir }}/private"}

- name: THD | update config
  tags: [containers, thd]
  copy:
    content: "{{ lookup('template', 'thd_config.template') }}"
    dest: "{{ thd_tmp_dir }}/thd_config.yaml"
    mode: 0755

- name: THD | start service
  tags: [containers, thd]
  docker_service:
    project_src: "{{ thd_tmp_dir }}"
    build: yes

# TODO: think of syncing telegram logs somewhere
