- include_vars: "{{ item }}"
  tags: [files]
  with_items:
    - files.yml
    - x11.yml
    - vpn.yml

- name: copy system files
  tags: [files, system]
  copy:
    src: "{{ role_path }}/files/{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0755
  become: yes
  with_items: "{{ system_files }}"

- name: copy auxillary files
  tags: [files, system]
  copy:
    content: "{{ lookup('template', 'system/{{ item }}') }}"
    dest: "/etc/{{ item }}"
    mode: 0755
  become: yes
  with_items: "{{ aux_files }}"

- name: copy homedir files
  tags: [files, home]
  copy:
    src: "{{ role_path }}/files/{{ item.src }}"
    dest: "{{ ansible_env.HOME }}/{{ item.dest }}"
    mode: 0755
  with_items: "{{ homedir_files }}"
