---

- include_vars: "{{ item }}"
  tags: [git]
  with_items:
    - git.yml
    - "{{ playbook_dir }}/../private/private_vars.yml"

- import_tasks: common.yml
  tags: [git]

- name: git | ensure paths
  tags: [git]
  file:
    path: "{{ item.path }}"
    state: directory
    mode: "{{ item.mode if 'mode' in item else 0755 }}"
    owner: "{{ item.user if 'user' in item else lookup('env', 'USER') }}"
    group: "{{ item.group if 'group' in item else current_user_primary_group }}"
    recurse: "{{ item.recurse if 'recurse' in item else 'yes' }}"
  become: "{{ item.become if 'become' in item else 'no' }}"
  with_items: "{{ git_paths }}"
  when: git_paths is defined and (('dists' in item and ansible_distribution in item.dists) or 'dists' not in item)

- name: git | instantiate templates
  tags: [git]
  copy:
    content: "{{ lookup('template', '{{ item.src }}') }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode if 'mode' in item else 0755 }}"
    owner: "{{ item.user if 'user' in item else lookup('env', 'USER') }}"
    group: "{{ item.group if 'group' in item else current_user_primary_group }}"
  become: "{{ item.become if 'become' in item else 'no' }}"
  with_items: "{{ git_templates }}"
  when: git_templates is defined and (('dists' in item and ansible_distribution in item.dists) or 'dists' not in item)
