---

- name: register current time
  shell: "date +%Y%m%d%H%M%S"
  register: current_run_timestamp
  tags: [always]

- import_tasks: shell.yml
- import_tasks: x11.yml
- import_tasks: misc.yml
- import_tasks: services.yml
- import_tasks: scanner.yml
- import_tasks: wm.yml
- import_tasks: system.yml
