- include_vars: misc.yml
  tags: [misc]

# TODO: put rc-update data under version control, e.g.:
# shell: rc-update add {{ item.name }} {{ item.level }}
# with_items: {{ rc_update_items }}
# and maybe export and delete all previous data before this

- name: add private hosts
  tags: [misc]
  blockinfile:
    dest: /etc/hosts
    block: "{{ private_hosts_data }}"
  become: yes
