---

- include_vars: "{{ item }}"
  tags: [misc, scripts, services, backup, restore, shepherd, imapfilter, thd]
  with_items:
    - misc.yml
    - "{{ playbook_dir }}/../private/private_vars.yml"
    - "{{ playbook_dir }}/../private/imap_filters.yml"

- import_tasks: misc.yml

- name: misc | accompanying tools | shepherd (scheduling) | copy jobs definitions
  tags: [misc, shepherd]
  copy:
    src: "{{ playbook_dir }}/../private/shepherd-jobs"
    dest: "{{ nixos_config_location }}/private/shepherd-jobs.yml"
    mode: 0755
