- include_vars: "{{ item }}"
  tags: [misc, backup, restore, shepherd, imapfilter, thd]
  with_items:
    - misc.yml
    - "{{ playbook_dir }}/../private/imap_filters.yml"

- import_tasks: common.yml
  tags: [misc]

- name: misc | ensure paths
  tags: [misc]
  file:
    path: "{{ item.path }}"
    state: directory
    mode: "{{ item.mode if 'mode' in item else 0755 }}"
    owner: "{{ item.user if 'user' in item else lookup('env', 'USER') }}"
    group: "{{ item.group if 'group' in item else current_user_primary_group }}"
    recurse: "{{ item.recurse if 'recurse' in item else 'yes' }}"
  become: "{{ item.become if 'become' in item else 'no' }}"
  with_items: "{{ misc_paths }}"
  when: misc_paths is defined and (('dists' in item and ansible_distribution in item.dists) or 'dists' not in item)

- name: misc | instantiate templates
  tags: [misc]
  copy:
    content: "{{ lookup('template', '{{ item.src }}') }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode if 'mode' in item else 0755 }}"
    owner: "{{ item.user if 'user' in item else lookup('env', 'USER') }}"
    group: "{{ item.group if 'group' in item else current_user_primary_group }}"
  become: "{{ item.become if 'become' in item else 'no' }}"
  with_items: "{{ misc_templates }}"
  when: misc_templates is defined and (('dists' in item and ansible_distribution in item.dists) or 'dists' not in item)

- name: misc | backup Emacs bookmarks
  tags: [misc, backup]
  copy:
    src: "{{ emacs_config_dir }}/data/bookmark-default.el"
    dest: "{{ playbook_dir }}/../private/bookmarks/bookmark-default.el"
    mode: 0755

- name: misc | restore Emacs bookmarks
  tags: [misc, restore]
  copy:
    src: "{{ playbook_dir }}/../private/bookmarks/bookmark-default.el"
    dest: "{{ emacs_config_dir }}/data/bookmark-default.el"
    mode: 0755

- name: misc | accompanying tools | shepherd (scheduling) | copy jobs definitions
  tags: [misc, shepherd]
  copy:
    src: "{{ playbook_dir }}/../private/shepherd-jobs"
    dest: "{{ ansible_env.HOME }}/shepherd-jobs.yml"
    mode: 0755
  notify: services | shepherd | restart service
  when: ansible_distribution == "Gentoo"

- name: misc | accompanying tools | shepherd (scheduling) | copy jobs definitions
  tags: [misc, shepherd]
  copy:
    src: "{{ playbook_dir }}/../private/shepherd-jobs"
    dest: "{{ ansible_env.HOME }}/shepherd-jobs.yml"
    mode: 0755
  when: ansible_distribution == "NixOS"

- name: misc | imapfilter | copy generated config file
  tags: [misc, imapfilter]
  copy:
    content: "{{ lookup('template', 'mail/imapfilter.conf.lua') }}"
    dest: "{{ ansible_env.HOME }}/.imapfilter/config.lua"
  notify:
    - services | imapfilter | restart service
  when: ansible_distribution == "Gentoo"

- name: misc | imapfilter | copy generated config file
  tags: [misc, imapfilter]
  copy:
    content: "{{ lookup('template', 'mail/imapfilter.conf.lua') }}"
    dest: "{{ ansible_env.HOME }}/.imapfilter/config.lua"
  when: ansible_distribution == "NixOS"
  # TODO: (alex3rd) define a service in NixOS configuration

# DISCLAIMER: at the moment most of started containers are planned to stop/remove manually

- name: misc | THD | prepare temporary dir
  tags: [misc, thd]
  file:
    path: "{{ thd_tmp_dir }}/private/downloads"
    state: directory
    mode: 0755
    recurse: yes

- name: misc | THD | prepare temporary dir
  tags: [misc, thd]
  copy:
    content: "{{ lookup('template', '{{ item.src }}') }}"
    dest: "{{ item.dest }}"
    mode: 0755
  with_items:
    - { src: "thd/Dockerfile-thd", dest: "{{ thd_tmp_dir }}/Dockerfile-thd" }
    - { src: "thd/config.j2", dest: "{{ thd_tmp_dir }}/thd_config.yaml" }
    - { src: "thd/docker-compose.yml", dest: "{{ thd_tmp_dir }}/docker-compose.yml" }
    - { src: "thd/thd.sh", dest: "{{ thd_tmp_dir }}/thd.sh" }

- name: misc | THD | extract binary part
  tags: [misc, thd]
  unarchive:
    src: "{{ playbook_dir }}/../private/telegram.tar.gz"
    dest: "{{ thd_tmp_dir }}/private"

- name: misc | THD | start service
  tags: [misc, thd]
  docker_service:
    project_src: "{{ thd_tmp_dir }}"
    build: yes
  when: ansible_distribution == "Gentoo" # TODO: (alex3rd) get docker-py installed on NixOS

- name: misc | mount some directories as tmpfs
  tags: [misc]
  lineinfile:
    dest: /etc/fstab
    line: 'tmpfs                   {{ item.path }}       tmpfs   uid={{ item.uid }},gid={{ item.gid }},size={{ item.size }},mode={{ item.mode }}      0 1'
    state: present
  become: yes
  with_items: "{{ tmpfs_paths }}"
  when: ansible_distribution == "Gentoo"
