- include_vars: "{{ item }}"
  tags: [paths, services]
  with_items:
    - paths.yml
    - vpn.yml
    - misc.yml

- name: ensure some system dirs exists
  tags: [paths, system]
  file:
    path: "{{ item }}"
    state: directory
  become: yes
  with_items: "{{ system_dirs }}"

- name: ensure home subdirs exist
  tags: [paths, home]
  file:
    path: "{{ ansible_env.HOME }}/{{ item }}"
    state: directory
  with_items: "{{ homedir_subdirs }}"

- name: mount user cache directory as tmpfs
  tags: [paths]
  lineinfile:
    dest: /etc/fstab
    line: 'tmpfs                   {{ user_cache_dir.path }}       tmpfs   uid={{ user_cache_dir.uid }},gid={{ user_cache_dir.gid }},size={{ user_cache_dir.size }},mode={{ user_cache_dir.mode }}      0 1'
    state: present
  become: yes
