---

- include_vars: portage.yml
  tags: [portage, bootstrap, overlays]

- import_tasks: common.yml
  tags: [portage, bootstrap]

- name: portage | ensure paths
  tags: [portage, bootstrap]
  file:
    path: "{{ item.path }}"
    state: directory
    mode: "{{ item.mode if 'mode' in item else 0755 }}"
    owner: "{{ item.user if 'user' in item else lookup('env', 'USER') }}"
    group: "{{ item.user if 'user' in item else lookup('env', 'USER') }}"
    recurse: "{{ item.recurse if 'recurse' in item else 'yes' }}"
  become: "{{ item.become if 'become' in item else 'no' }}"
  with_items: "{{ portage_paths }}"
  when: portage_paths is defined

- name: portage | instantiate templates
  tags: [portage, bootstrap]
  copy:
    content: "{{ lookup('template', '{{ item.src }}') }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode if 'mode' in item else 0755 }}"
    owner: "{{ item.user if 'user' in item else lookup('env', 'USER') }}"
    group: "{{ item.user if 'user' in item else lookup('env', 'USER') }}"
  become: "{{ item.become if 'become' in item else 'no' }}"
  with_items: "{{ portage_templates }}"
  when: portage_templates is defined

- name: portage | ensure Layman installed
  tags: [portage]
  portage:
    package: app-portage/layman
    state: present
  become: yes
  when:
    - portage_check_packages_installed

- name: portage | instantiate Layman config
  tags: [portage, overlays]
  copy:
    content: "{{ lookup('template', 'layman/layman.cfg.j2') }}"
    dest: "/etc/layman/layman.cfg"
    mode: 0755
  become: yes

- name: portage | get installed overlays
  tags: [portage, overlays]
  find:
    paths: "{{ portage_overlays_data_location }}"
    file_type: directory
  register: overlays_installed

- name: portage | ensure needed overlays
  tags: [portage, overlays]
  layman:
    name: "{{ item }}"
    state: present
  become: yes
  with_items: "{{ portage_overlays }}"
  notify:
    - portage | fix overlays permissions
    - portage | update tree status

- name: portage | remove obsolete overlays
  tags: [portage, overlays]
  layman:
    name: "{{ item.path | basename }}"
    state: absent
  become: yes
  with_items: "{{ overlays_installed.files }}"
  when: "item.path | basename not in portage_overlays"
  notify: portage | update tree status

- name: portage | copy local overlay files
  tags: [portage, overlays]
  synchronize:
    src: "{{ role_path }}/files/portage/local_overlay/"
    dest: "{{ portage_local_overlay_data_location }}"
    recursive: yes
    delete: yes
  become: yes
  notify: portage | fix local overlay permissions

# TODO think of moving this to shell level
# consult with "world" file
# reduce time for checks
- name: portage | ensure some packages installed
  tags: [portage]
  portage:
    package: "{{ item }}"
    state: present
  with_items: "{{ packages_of_interest }}"
  become: yes
  when:
    - portage_check_packages_installed

- name: portage | mount build directory as tmpfs
  tags: [portage]
  lineinfile:
    dest: /etc/fstab
    line: 'tmpfs                   {{ portage_build_dir.path }}       tmpfs   uid={{ portage_build_dir.uid }},gid={{ portage_build_dir.gid }},size={{ portage_build_dir.size }},mode={{ portage_build_dir.mode }}      0 1'
    state: present
  become: yes
