---

- include_vars: "{{ item }}"
  tags: [python]
  with_items:
    - python.yml
    - "{{ playbook_dir }}/../private/private_vars.yml"

- import_tasks: common.yml
  tags: [python]

- name: python | install pip packages
  tags: [python]
  pip:
    name: "{{ item }}"
    state: latest
    extra_args: --user
  with_items: "{{ python_pip_packages }}"
  when: ansible_distribution == "Gentoo"

- name: python | ensure paths
  tags: [python]
  file:
    path: "{{ item.path }}"
    state: directory
    mode: "{{ item.mode if 'mode' in item else 0755 }}"
    owner: "{{ item.user if 'user' in item else lookup('env', 'USER') }}"
    group: "{{ item.group if 'group' in item else current_user_primary_group }}"
    recurse: "{{ item.recurse if 'recurse' in item else 'yes' }}"
  become: "{{ item.become if 'become' in item else 'no' }}"
  with_items: "{{ python_paths }}"
  when: python_paths is defined and (('dists' in item and ansible_distribution in item.dists) or 'dists' not in item)

- name: python | instantiate templates
  tags: [python]
  copy:
    content: "{{ lookup('template', '{{ item.src }}') }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode if 'mode' in item else 0755 }}"
    owner: "{{ item.user if 'user' in item else lookup('env', 'USER') }}"
    group: "{{ item.group if 'group' in item else current_user_primary_group }}"
  become: "{{ item.become if 'become' in item else 'no' }}"
  with_items: "{{ python_templates }}"
  when: python_templates is defined and (('dists' in item and ansible_distribution in item.dists) or 'dists' not in item)
