- include_vars: services.yml
  tags: [services, shepherd, sshuttle, imapfilter, syndaemon]

- name: services | shepherd | install openrc entry
  tags: [services, shepherd]
  copy:
    content: "{{ lookup('template', 'services/shepherd.openrc') }}"
    dest: "/etc/init.d/shepherd"
    mode: 0755
  become: yes

- name: services | sshuttle | install openrc entry
  tags: [services, sshuttle]
  copy:
    content: "{{ lookup('template', 'services/sshuttle.openrc') }}"
    dest: "/etc/init.d/sshuttle"
    mode: 0755
  become: yes

- name: services | imapfilter | install openrc entry
  tags: [services, imapfilter]
  copy:
    content: "{{ lookup('template', 'services/imapfilter.openrc') }}"
    dest: "/etc/init.d/imapfilter"
    mode: 0755
  become: yes
