- include_vars: services.yml
  tags: [services, shepherd, sshuttle]

- name: services | shepherd | install openrc entry
  tags: [services, shepherd]
  copy:
    content: "{{ lookup('template', 'services/shepherd.openrc') }}"
    dest: "/etc/init.d/shepherd"
    mode: 0755
  become: yes

- name: services | shepherd | restart service
  tags: [services, shepherd]
  service:
    name: shepherd
    state: restarted
  become: yes

- name: services | shepherd | install openrc entry
  tags: [services, sshuttle]
  copy:
    content: "{{ lookup('template', 'services/sshuttle.openrc') }}"
    dest: "/etc/init.d/sshuttle"
    mode: 0755
  become: yes

- name: services | shepherd | restart service
  tags: [services, sshuttle]
  service:
    name: sshuttle
    state: restarted
  become: yes

- name: services | shepherd | install openrc entry
  tags: [services, imapfilter]
  copy:
    content: "{{ lookup('template', 'services/imapfilter.openrc') }}"
    dest: "/etc/init.d/imapfilter"
    mode: 0755
  become: yes

- name: services | shepherd | restart service
  tags: [services, imapfilter]
  service:
    name: imapfilter
    state: restarted
  become: yes
