- include_vars: shells.yml
  tags: [shells, bash, zsh, tmux, backup, restore]

- import_tasks: common.yml
  tags: [shells]

- name: shell | ensure paths
  tags: [shells]
  file:
    path: "{{ item.path }}"
    state: directory
    mode: "{{ item.mode if 'mode' in item else 0755 }}"
    owner: "{{ item.user if 'user' in item else lookup('env', 'USER') }}"
    group: "{{ item.user if 'user' in item else lookup('env', 'USER') }}"
    recurse: "{{ item.recurse if 'recurse' in item else 'yes' }}"
  become: "{{ item.become if 'become' in item else 'no' }}"
  with_items: "{{ shell_paths }}"
  when: shell_paths is defined

- name: shell | instantiate templates
  tags: [shells]
  copy:
    content: "{{ lookup('template', '{{ item.src }}') }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode if 'mode' in item else 0755 }}"
    owner: "{{ item.user if 'user' in item else lookup('env', 'USER') }}"
    group: "{{ item.user if 'user' in item else lookup('env', 'USER') }}"
  become: "{{ item.become if 'become' in item else 'no' }}"
  with_items: "{{ shell_templates }}"
  when: shell_templates is defined

- name: shell | ensure groups exist
  tags: [shells]
  group:
    name: "{{ item }}"
    state: present
  with_items: "{{ default_user_groups }}"
  become: yes

- name: shell | ensure default user traits
  tags: [shells]
  user:
    name: "{{ default_user_name }}"
    shell: "{{ user_shell_binaries[default_user_shell] }}"
    groups: "{{ default_user_groups | join(',') }}"
  become: yes

- name: shell | instantiate common settings
  tags: [shells]
  copy:
    content: "{{ lookup('template', 'shell/{{ item }}.template') }}"
    dest: "{{ ansible_env.HOME }}/{{ item }}"
    mode: 0755
  with_items:
    - "{{ common_settings_basenames }}"

- name: shell | check if .bashrc exists
  tags: [shells, bash]
  stat: path={{ ansible_env.HOME }}/.bashrc
  register: bashrc

- name: shell | source common settings
  tags: [shells, bash]
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.bashrc"
    line: "source ~/common_settings_bash"
    state: present
  when:
    - bashrc.stat.exists == True

- name: shell | Antibody | generate plugins list
  tags: [shells, zsh]
  copy:
    content: "{{ lookup('template', 'shell/zsh.plugins.template') }}"
    dest: "{{ zsh_plugins_list_location }}"
    mode: 0755

- name: shell | Antibody | bundle plugins statically
  tags: [shells, zsh]
  shell: "{{ zsh_plugins_antibody_bundle_command }}"

- name: shell | instantiate .zshrc
  tags: [shells, zsh]
  copy:
    content: "{{ lookup('template', 'shell/.zshrc.template') }}"
    dest: "{{ ansible_env.HOME }}/.zshrc"
    mode: 0755

- name: shell | tmux | instantiate sessions script
  tags: [shell, tmux]
  copy:
    content: "{{ lookup('template', 'shell/tmux-sessions.template') }}"
    dest: "{{ ansible_env.HOME }}/tmux-sessions"
    mode: 0755

- name: shell | backup bookmarks
  tags: [shells, backup]
  copy:
    src: "{{ ansible_env.HOME }}/.bookmarks"
    dest: "{{ playbook_dir }}/../private/bookmarks/.bookmarks"
    mode: 0755

- name: shell | restore bookmarks
  tags: [shells, restore]
  copy:
    src: "{{ playbook_dir }}/../private/bookmarks/.bookmarks"
    dest: "{{ ansible_env.HOME }}/.bookmarks"
    mode: 0755
