---

- include_vars: system.yml
  tags: [system, kernel, permissions]

- import_tasks: common.yml
  tags: [system]

- name: system | ensure paths
  tags: [system]
  file:
    path: "{{ item.path }}"
    state: directory
    mode: "{{ item.mode if 'mode' in item else 0755 }}"
    owner: "{{ item.user if 'user' in item else lookup('env', 'USER') }}"
    group: "{{ item.group if 'group' in item else current_user_primary_group }}"
    recurse: "{{ item.recurse if 'recurse' in item else 'yes' }}"
  become: "{{ item.become if 'become' in item else 'no' }}"
  with_items: "{{ system_paths }}"
  when: system_paths is defined and (('dists' in item and ansible_distribution in item.dists) or 'dists' not in item)

- name: system | instantiate templates
  tags: [system]
  copy:
    content: "{{ lookup('template', '{{ item.src }}') }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode if 'mode' in item else 0755 }}"
    owner: "{{ item.user if 'user' in item else lookup('env', 'USER') }}"
    group: "{{ item.group if 'group' in item else current_user_primary_group }}"
  become: "{{ item.become if 'become' in item else 'no' }}"
  with_items: "{{ system_templates }}"
  when: system_templates is defined and (('dists' in item and ansible_distribution in item.dists) or 'dists' not in item)

- name: ensure particular Linux kernel flags
  tags: [system, kernel]
  lineinfile:
    path: "{{ system_kernel_config_file }}"
    regexp: "^CONFIG_{{ item.name }}=[ym1234567890]|^# CONFIG_{{ item.name }} is not set" # (alex3rd) regexp is too permissive, but does the trick
    line: "{% if item.value == 'n' %}# CONFIG_{{ item.name }} is not set{% else %}CONFIG_{{ item.name }}={{ item.value }}{% if system_kernel_dump_labels and item.labels | length > 0 %} # {{ item.labels | join(', ')}}{% endif %}{% endif %}"
    state: present
  with_items: "{{ system_kernel_flags | rejectattr('disabled', 'sameas', true) | list }}"
  become: yes
  when: ansible_distribution == "Gentoo"

- name: query Linux kernel source directory symlink
  tags: [system, kernel, permissions]
  stat:
    path: /usr/src/linux
  register: linux_kernel_symlink
  when: ansible_distribution == "Gentoo"

- name: fix kernel artifacts permissions
  tags: [system, kernel, permissions]
  file:
    path: "{{ item }}"
    owner: root
    group: root
    mode: 0777
    recurse: yes
  with_items:
    - "{{ linux_kernel_symlink.stat.lnk_source }}"
    - "/lib/modules/{{ '-'.join(linux_kernel_symlink.stat.lnk_target.split('-')[1:]) }}"
  become: yes
  when: ansible_distribution == "Gentoo"

- name: setup services autostart
  tags: [system]
  service:
    name: "{{ item.name }}"
    enabled: yes
    runlevel: "{{ item.runlevel }}"
    state: "{{ item.status }}"
  with_items: "{{ system_services }}"
  become: yes
  when: ansible_distribution == "Gentoo"
