---

- include_vars: vpn.yml
  tags: [vpn, services]

- import_tasks: common.yml
  tags: [vpn]

- import_tasks: vpn.yml
  tags: [vpn]

- name: vpn | customize OpenVPN config | fix up/down scripting
  tags: [vpn]
  lineinfile:
    dest: "{{ job_vpn_datadir }}/office.ovpn"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: "^up /etc/openvpn/update-resolv-conf", line: "up /etc/openvpn/up.sh" }
    - { regexp: "^down /etc/openvpn/update-resolv-conf", line: "down /etc/openvpn/down.sh" }
  become: yes
  notify: stop vpn service

- name: vpn | install openrc entry
  tags: [vpn, services]
  copy:
    content: "{{ lookup('template', 'services/{{ vpn_service_name }}.openrc') }}"
    dest: "/etc/init.d/{{ vpn_service_name }}"
    mode: 0755
  become: yes
  notify: stop vpn service
