- include_vars: "{{ item }}"
  tags: [always]
  with_items:
    - x11.yml

- name: stumpwm | clone repo
  tags: [wm, stumpwm]
  git:
    repo: "{{ x11_stumpwm_traits.clone_from }}"
    dest: "{{ x11_stumpwm_traits.local_path }}"
    force: yes

- name: stumpwm | check configure script
  tags: [wm, stumpwm]
  stat: path={{ x11_stumpwm_traits.local_path }}/configure
  register: stumpwm_configure

- name: stumpwm | maybe autoconf
  tags: [wm, stumpwm]
  shell: autoconf
  args:
    chdir: "{{ x11_stumpwm_traits.local_path }}"
  when:
    - stumpwm_configure.stat.exists == False

- name: stumpwm | configure
  tags: [wm, stumpwm]
  shell: ./configure
  args:
    chdir: "{{ x11_stumpwm_traits.local_path }}"

- name: stumpwm | patch binary image creation
  tags: [wm, stumpwm]
  lineinfile:
    path: "{{ x11_stumpwm_traits.local_path }}/make-image.lisp"
    insertafter: ":executable t"
    line: "                                    :compression t"

- name: stumpwm | build
  tags: [wm, stumpwm]
  make:
    chdir: "{{ x11_stumpwm_traits.local_path }}"

- name: stumpwm | install
  tags: [wm, stumpwm]
  make:
    chdir: "{{ x11_stumpwm_traits.local_path }}"
    target: install
  become: yes

- name: generate shell settings for StumpWM
  tags: [wm, stumpwm]
  copy:
    content: "{{ lookup('template', 'shell/shell.lisp.template') }}"
    dest: "{{ stumpwm_config_path }}/shell.lisp"
    mode: 0755
