- include_vars: "{{ item }}"
  tags: [always]
  with_items:
    - x11.yml
    - fs.yml
    - misc.yml

- import_tasks: common.yml
  tags: [x11]

- name: instantiate templated configs
  tags: [x11, templated]
  copy:
    content: "{{ lookup('template', '{{ item.src }}') }}"
    dest: "{{ ansible_env.HOME }}/{{ item.dest }}"
    mode: 0755
  with_items: "{{ x11_templated_configs }}"

- name: register org-protocol handler in mimeapps
  tags: [x11]
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.local/share/applications/mimeapps.list"
    line: x-scheme-handler/org-protocol=emacsclient.desktop
    state: present

- name: instantiate resources configs
  tags: [x11, configs]
  copy:
    content: "{{ lookup('template', '{{ item.src }}') }}"
    dest: "{{ ansible_env.HOME }}/{{ item.dest }}"
    mode: 0755
  with_items: "{{ x11_resources_configs }}"

- name: setup xdg-open associations
  tags: [x11]
  shell: "xdg-mime default {{ item.program }}.desktop {{ item.mimetype }}"
  with_items: "{{ mime_assocs }}"

- name: update MIME types DB
  tags: [x11]
  shell: "update-desktop-database ~/.local/share/applications/"

- name: generate OSD statusbar script
  tags: [x11]
  copy:
    content: "{{ lookup('template', 'x11/statusbar_osd.template') }}"
    dest: "{{ binaries_prefix }}/statusbar_osd"
    mode: 0755
    owner: "{{ user_name }}"
    group: "{{ user_group }}"

- name: generate .xsession script
  tags: [x11]
  copy:
    content: "{{ lookup('template', 'x11/.xsession.template') }}"
    dest: "{{ ansible_env.HOME }}/.xsession"
    mode: 0755
  register: xsession_script

- name: copy xrandr scripts
  tags: [x11, scripts]
  copy:
    content: "{{ lookup('template', 'x11/xrandr/{{ item | basename }}') }}"
    dest: "/usr/local/bin/{{ item | basename }}"
    mode: 0755
  with_fileglob:
    - "{{ role_path }}/templates/x11/xrandr/*"
  become: yes

- name: remove tangled Emacs config
  tags: [x11]
  file:
    path: "{{ emacs_config_name_tangled }}"
    state: absent
  when:
    - xsession_script.changed
