#!/bin/sh
BAT_NAME="BAT0"
UPOWER_ENERGY_FULL_DESIGN=$(upower -i /org/freedesktop/UPower/devices/battery_$BAT_NAME | grep "energy-full-design:" | cut -f 14 -d " ")
UPOWER_ENERGY_FULL_FACT=$(upower -i /org/freedesktop/UPower/devices/battery_$BAT_NAME | grep "energy-full:" | cut -f 14 -d " ")
UPOWER_PERCENTAGE=$(upower -i /org/freedesktop/UPower/devices/battery_$BAT_NAME | grep "percentage:" | cut -f 15 -d " ")
UPOWER_STATE=$(upower -i /org/freedesktop/UPower/devices/battery_$BAT_NAME | grep "state:" | cut -f 20 -d " ")
case $UPOWER_STATE in
	fully-charged)
		st="="
		;;
	discharging)
		st="-"
		;;
	charging)
		st="+"
		;;
esac
echo $st$UPOWER_PERCENTAGE
