---

emerge_check_packages_installed: no
emerge_packages_of_interest:
  - "app-admin/apache-tools"
  - "app-admin/kubectx"
  - "app-admin/pass"
  - "app-admin/vault"
  - "app-arch/upx-ucl"          # or proprietary-like app-arch/upx-bin + try to build from https://github.com/upx/upx
  - "app-benchmarks/wrk"
  - "app-doc/zeal"
  - "app-emacs/auctex"
  - "app-emacs/haskell-mode"
  - "app-emulation/docker"
  - "app-emulation/docker-compose"
  - "app-emulation/docker-machine"
  - "app-emulation/docker-swarm"
  - "app-misc/diff-so-fancy"
  - "app-misc/exercism"
  - "app-misc/jq"
  - "app-misc/jrnl"
  - "app-misc/tmux"
  - "app-misc/tmux-mem-cpu-load"
  - "app-misc/wmname"
  - "app-misc/workrave"
  - "app-office/ledger"
  - "app-shells/antibody"
  - "app-shells/fzf"
  - "app-text/pandoc"
  - "dev-lisp/cl-launch"
  - "dev-lua/luacheck"
  - "dev-lua/luvit"
  - "dev-python/appdirs"
  - "dev-python/blockdiag"
  - "dev-python/mypy"
  - "dev-python/watchdog"
  - "dev-util/cargo"
  - "dev-util/debugedit"
  - "dev-util/direnv"
  - "dev-util/gengetopt"
  - "dev-util/lockrun"
  - "dev-util/ltrace"
  - "dev-util/plan9port"
  - "dev-util/rtags"
  - "dev-util/strace"
  - "dev-vcs/git-annex"
  - "gnome-extra/nm-applet"
  - "mail-filter/imapfilter"
  - "media-gfx/exif"
  - "media-gfx/imagemagick"
  - "media-gfx/maim"
  - "media-gfx/plantuml"
  - "media-libs/exiftool"
  - "media-sound/volumeicon"
  - "net-im/telegram-cli"
  - "net-irc/weechat"
  - "net-mail/notmuch-addrlookup"
  - "net-misc/dhcpcd"
  - "net-misc/dhcpcd-ui"
  - "net-misc/dropbox"
  - "net-misc/httpie"
  - "net-misc/mosh"
  - "net-misc/rclone-bin"
  - "net-misc/urlview"
  - "sys-apps/dbus"
  - "sys-apps/exa"
  - "sys-apps/fbset"
  - "sys-apps/highway"
  - "sys-apps/lm_sensors"
  - "sys-apps/moreutils"
  - "sys-apps/ripgrep"
  - "sys-devel/gdb"
  - "sys-fs/dfc"
  - "sys-fs/udiskie"
  - "sys-fs/udisks"
  - "sys-libs/gpm"
  - "sys-power/acpi"
  - "sys-power/upower-pm-utils"
  - "x11-apps/arbtt"
  - "x11-apps/intel-gpu-tools"
  - "x11-apps/xev"
  - "x11-apps/xhost"
  - "x11-apps/xinput"
  - "x11-apps/xinput_calibrator"
  - "x11-apps/xmodmap"
  - "x11-apps/xprop"
  - "x11-apps/xrdb"
  - "x11-apps/xwininfo"
  - "x11-libs/xosd"
  - "x11-misc/autocutsel"
  - "x11-misc/dex"
  - "x11-misc/dzen"
  - "x11-misc/kbdd"
  - "x11-misc/redshift"
  - "x11-misc/trayer-srg"
  - "x11-misc/unclutter"
  - "x11-misc/wmctrl"
  - "x11-misc/xclip"
  - "x11-misc/xdg-user-dirs"
  - "x11-misc/xdotool"
  - "x11-misc/xkbset"
  - "x11-misc/xprintidle"
  - "x11-misc/xsel"
  - "x11-misc/xxkb"
  - "x11-misc/yeganesh"
  - "x11-terms/rxvt-unicode"
emerge_packages_disabled:
  - "app-forensics/afl" # broken at the moment
  - "app-forensics/sleuthkit" # broken at the moment
  - "dev-vcs/git-extras" # later
  - "app-crypt/hashcat"
