---

python_pip_packages:
  - "GitPython"
  - "autopep8"
  - "flake8"
  - "imapautofiler"
  - "importmagic"
  - "isort"
  - "jedi"
  - "jmespath"
  - "olefile"
  - "rst2pdf"
  - "snakeviz"
  - "traad"
  - "virtualenvwrapper"
  - "yapf"
