---

- include_vars: custom.yml
  tags: [always]

- name: accompanying tools | shepherd (scheduling) | get
  tags: [custom, shepherd]
  git:
    repo: "{{ shepherd_traits.clone_from }}"
    dest: "{{ shepherd_traits.local_path }}"
    force: yes

- name: accompanying tools | shepherd (scheduling) | build
  tags: [custom, shepherd]
  shell: go build -o shepherd main.go
  args:
    chdir: "{{ shepherd_traits.local_path }}"

- name: accompanying tools | shepherd (scheduling) | install
  tags: [custom, shepherd]
  shell: "mv {{ shepherd_traits.local_path }}/{{ shepherd_traits.binary }} {{ binaries_prefix }}/{{ shepherd_traits.binary }}"
  become: yes

- name: install tmux plugin manager
  tags: [custom, tmux]
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: "{{ ansible_env.HOME }}/.tmux/plugins/tpm"

- name: Buildapp | clone repo
  tags: [custom, buildapp]
  git:
    repo: "{{ buildapp_traits.clone_from }}"
    dest: "{{ buildapp_traits.local_path }}"
    force: yes

- name: Buildapp
  tags: [custom, buildapp]
  make:
    chdir: "{{ buildapp_traits.local_path }}"
    target: "{{ item }}"
  with_items:
    - buildapp
    - install
  become: yes

- name: git-quick-stats | clone repository
  tags: [custom, gqs]
  git:
    repo: "{{ gqs_traits.clone_from }}"
    dest: "{{ gqs_traits.local_path }}"
    force: yes

- name: git-quick-stats | install
  tags: [custom, gqs]
  make:
    chdir: "{{ gqs_traits.local_path }}"
    target: install
  become: yes

- name: git-quick-stats | set permissions
  tags: [custom, gqs]
  file:
    path: "{{ binaries_prefix }}/git-quick-stats"
    mode: 0755
    owner: "{{ user_name }}"
    group: "{{ user_group }}"
  become: yes

- name: git-quick-stats | uninstall
  tags: [custom, gqs]
  make:
    chdir: "{{ gqs_traits.local_path }}"
    target: uninstall
  when:
    - False # invoke directly

- name: download Telegram Desktop archive
  tags: [custom, tg]
  get_url:
    url: "https://updates.tdesktop.com/tlinux/tsetup.{{ telegram_version }}.tar.xz"
    dest: /tmp/tsetup.tar.xz
    force: yes

- name: update Telegram Desktop binaries
  tags: [custom, tg]
  unarchive:
    src: /tmp/tsetup.tar.xz
    dest: /usr/local/bin
    extra_opts:
      - "--strip=1"
  become: yes

# TODO: think of TG themes automation

- name: tmuxifier | clone repo
  tags: [custom, tmuxifier]
  git:
    repo: "{{ tmuxifier_traits.clone_from }}"
    dest: "{{ tmuxifier_traits.local_path }}"
    force: yes

- name: httplab | install
  tags: [custom, golang]
  shell: go get github.com/gchaincl/httplab

# TODO: https://github.com/asciimoo/wuzz - master/HEAD is broken (SIGSEGV), try later

- name: Zshnip | clone repo
  tags: [custom, zshnip]
  git:
    repo: "{{ zshnip_traits.clone_from }}"
    dest: "{{ zshnip_traits.local_path }}"
    force: yes

- name: Zshnip | copy file(s)
  tags: [custom, zshnip]
  copy:
    src: "{{ zshnip_traits.local_path }}/zshnip.zsh"
    dest: "/usr/local/bin"
    mode: 0755
  become: yes

- name: hr | clone repository
  tags: [custom, hr]
  git:
    repo: "{{ hr_traits.clone_from }}"
    dest: "{{ hr_traits.local_path }}"
    force: yes

- name: hr | install
  tags: [custom, hr]
  make:
    chdir: "{{ hr_traits.local_path }}"
    target: install
  become: yes

- name: tbdiff | clone repository
  tags: [custom, tbdiff]
  git:
    repo: "{{ tbdiff_traits.clone_from }}"
    dest: "{{ tbdiff_traits.local_path }}"
    force: yes

- name: tbdiff | install
  tags: [custom, tbdiff]
  copy:
    src: "{{ tbdiff_traits.local_path }}/git-tbdiff.py"
    dest: "/usr/local/bin/git-tbdiff"
    mode: 0755
    owner: "{{ user_name }}"
    group: "{{ user_group }}"
  become: yes
