---

- include_vars: golang.yml
  tags: [golang]

- name: check packages installed
  tags: [golang]
  stat:
    path: "{{ golang_src_path }}/{{ item.url }}"
  register: packages_paths
  with_items: "{{ golang_package_urls }}"

- name: install Go packages from source
  tags: [golang]
  command: "go get -u {{ item.0.url }}"
  with_together:
    - "{{ golang_package_urls }}"
    - "{{ packages_paths.results }}"
  become: "{{ item.0.become }}"
  when: "not item.1.stat.exists"

- name: symlink Go tools binaries to mainstream path
  tags: [golang]
  file:
    src: "{{ item }}"
    dest: "/usr/bin/{{ item | basename }}"
    state: link
  with_fileglob:
    - "{{ golang_bin_path }}/*"
  become: yes
  ignore_errors: yes
