---

- include_vars: python.yml
  tags: [python]

- name: python | install pip packages
  tags: [python]
  pip:
    name: "{{ item }}"
    state: latest
    extra_args: --user
  with_items: "{{ python_pip_packages }}"
