---

- name: services | shepherd | restart service
  service:
    name: shepherd
    state: restarted
  become: yes

# TODO: find a way to trigger this
- name: services | sshuttle | restart service
  service:
    name: sshuttle
    state: restarted
  become: yes

- name: services | imapfilter | restart service
  service:
    name: imapfilter
    state: restarted
  become: yes
