---

binaries_prefix:
  Gentoo:
    path: /usr/local/bin
    become: yes
  NixOS:
    path: "{{ ansible_env.HOME }}/scripts"
user_name: octocat
user_group: octocat
pids_dir: "{{ ansible_env.HOME }}/pids"
custom_vpn_datadir: /etc/custom_vpn
workspace_path: "{{ ansible_env.HOME }}/workspace"
home_config_path: "{{ ansible_env.HOME }}/.config"
