---

insecure_docker: no
docker_machine_traits: { clone_from: "https://github.com/docker/machine", local_path: "/tmp/docker-machine" }
zsh_subconfig_path: "{{ ansible_env.HOME}}/.zsh"
virt_vagrant_common_box_name: ubuntu/xenial64
