---

- name: register current time
  shell: "date +%Y%m%d%H%M%S"
  register: current_run_timestamp
  tags: [always]

- name: ensure some system dirs exists
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  become: yes
  with_items: "{{ system_dirs }}"
  when:
    - "'bootstrap' in actions"

- name: copy Portage files
  copy:
    src: "{{ role_path }}/files/portage/{{ item }}"
    dest: "/etc/portage/{{ item }}"
    mode: 0755
  become: yes
  with_items: "{{ portage_files }}"
  when:
    - "'setup' in actions"

- name: copy auxillary files
  copy:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "/etc/{{ item }}"
    mode: 0755
  become: yes
  with_items: "{{ aux_files }}"
  when:
    - "'setup' in actions"

- name: ensure Layman installed
  portage:
    package: app-portage/layman
    state: present
  become: yes
  when:
    - "'setup' in actions"
    - check_packages_installed

- name: instantiate Layman config
  copy:
    content: "{{ lookup('template', 'layman.cfg.template') }}"
    dest: "/etc/layman/layman.cfg"
    mode: 0755
  become: yes
  when:
    - "'setup' in actions"

- name: ensure overlays
  layman:
    name: "{{ item }}"
    state: present
  become: yes
  with_items: "{{ portage_overlays }}"
  register: overlays
  when:
    - "'setup' in actions"

- name: fix overlays permissions
  file:
    path: "/var/lib/layman/{{ item }}"
    owner: portage
    group: portage
    mode: 0755
    recurse: yes
  become: yes
  # become_user: portage
  with_items: "{{ portage_overlays }}"
  when:
    - "'setup' in actions"

- name: update portage tree status
  shell: eix-update
  become: yes
  when: overlays.changed

# TODO think of moving this to shell level
# consult with "world" file
# reduce time for checks
- name: ensure some packages installed
  portage:
    package: "{{ item }}"
    state: present
  with_items: "{{ packages_of_interest }}"
  become: yes
  when:
    - "'setup' in actions"
    - check_packages_installed

- name: copy local overlay files
  copy:
    src: "{{ role_path }}/files/portage/local_overlay/"
    dest: /usr/local/portage
    owner: portage
    group: portage
    mode: 0755
  become: yes
  when:
    - "'setup' in actions"

- name: mount portage build directory as tmpfs
  lineinfile:
    dest: /etc/fstab
    line: 'tmpfs                   /var/tmp/portage/       tmpfs   uid=250,gid=250,size=10G,mode=0775      0 1'
    state: present
  become: yes
  when:
    - "'setup' in actions"
