---

- name: copy auxillary files
  tags: [aux]
  copy:
    content: "{{ lookup('template', '{{ item }}') }}"
    dest: "/etc/{{ item }}"
    mode: 0755
  become: yes
  with_items: "{{ aux_files }}"

- name: mount user cache directory as tmpfs
  tags: [aux]
  lineinfile:
    dest: /etc/fstab
    line: 'tmpfs                   {{ user_cache_dir.path }}       tmpfs   uid={{ user_cache_dir.uid }},gid={{ user_cache_dir.gid }},size={{ user_cache_dir.size }},mode={{ user_cache_dir.mode }}      0 1'
    state: present
  become: yes

# TODO: https://wiki.gentoo.org/wiki/Intel#Brightness_does_not_change_with_keyboard_shortcuts
